/**
 * Emotion cache registry for Next.js App Router.
 *
 * This component ensures that MUI's Emotion styles are properly
 * injected during server-side rendering and hydration.
 */

"use client";

import React from "react";
import { useServerInsertedHTML } from "next/navigation";
import { CacheProvider } from "@emotion/react";
import createCache from "@emotion/cache";

interface EmotionRegistryProps {
  children: React.ReactNode;
}

/**
 * Emotion registry component for Next.js App Router.
 *
 * This component creates a stable emotion cache and injects
 * styles into the document during SSR.
 *
 * @param props - Component props
 * @returns Registry component
 */
export function EmotionRegistry({ children }: EmotionRegistryProps) {
  const [cache] = React.useState(() => {
    const cache = createCache({ key: "css", prepend: true });
    cache.compat = true;
    return cache;
  });

  // SECURITY: Safe — Emotion CSS cache output. Content is generated by
  // MUI/Emotion from component styles, not from user input.
  useServerInsertedHTML(() => {
    return (
      <style
        data-emotion={`${cache.key} ${Object.keys(cache.inserted).join(" ")}`}
        dangerouslySetInnerHTML={{
          __html: Object.values(cache.inserted).join(" "),
        }}
      />
    );
  });

  return <CacheProvider value={cache}>{children}</CacheProvider>;
}

