# Copyright (c) 2025 Databricks, Inc.
# Licensed under the Databricks Open Model License. See LICENSE for the full text.
"""Unit tests for the aitools distribution mirror and manifest.

Validates that:
1. The generated mirror matches the canonical skills roster.
2. The manifest.json conforms to its declared schema.
3. Every skill in the mirror has valid frontmatter (per the Agent Skills spec
   and the ai-dev-kit validate_skills.py rules — agentskills.io/specification).
4. Regenerating the mirror (``python scripts/skills.py``) is idempotent: skill
   file content is stable across runs (``generated_at`` in manifest.json changes
   per-run by design and is excluded from the stability check).

These tests ride ``make test-unit`` (CI-collected) and are deliberately
side-effect-free: they read from the committed mirror + manifest, do NOT
execute the generation script (test #4 uses filecmp, not a subprocess), and
therefore impose no network or filesystem write requirements in CI.

The committed mirror at ``packages/starboard-distribution/aitools/`` is
generated by ``python scripts/skills.py`` and must be regenerated whenever the
canonical skills tree changes.  Run ``make test-distribution`` (see note in
reports) to detect drift.
"""

from __future__ import annotations

import filecmp
import json
import re
from pathlib import Path

import pytest
import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

def _repo_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "packages" / "starboard-skills" / "skills").is_dir():
            return parent
    raise AssertionError(
        "could not locate repo root containing packages/starboard-skills/skills"
    )


REPO_ROOT = _repo_root()
CANONICAL_SKILLS_ROOT = REPO_ROOT / "packages" / "starboard-skills" / "skills" / "starboard"
MIRROR_ROOT = REPO_ROOT / "packages" / "starboard-distribution" / "aitools"
MANIFEST_PATH = MIRROR_ROOT / "manifest.json"

# Expected roster from the canonical tree
EXPECTED_SKILL_COUNT = 10

# ---------------------------------------------------------------------------
# Agent Skills spec constraints (agentskills.io/specification) —
# same rules enforced by ai-dev-kit validate_skills.py
# ---------------------------------------------------------------------------

_NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
_XML_TAG_RE = re.compile(r"<[^>]+>")
_RESERVED_WORDS = {"anthropic", "claude"}
NAME_MAX = 64
DESCRIPTION_MAX = 1024
_FRONTMATTER_RE = re.compile(r"\A---\r?\n(?P<yaml>.*?)\r?\n---\r?\n", re.DOTALL)


def _parse_frontmatter(text: str) -> dict:
    match = _FRONTMATTER_RE.match(text)
    assert match is not None, "SKILL.md must open with fenced YAML frontmatter"
    data = yaml.safe_load(match.group("yaml"))
    assert isinstance(data, dict), "frontmatter must parse to a YAML mapping"
    return data


def _canonical_skill_names() -> list[str]:
    if not CANONICAL_SKILLS_ROOT.is_dir():
        return []
    return sorted(p.name for p in CANONICAL_SKILLS_ROOT.iterdir() if p.is_dir())


def _mirror_skill_names() -> list[str]:
    if not MIRROR_ROOT.is_dir():
        return []
    return sorted(
        p.name
        for p in MIRROR_ROOT.iterdir()
        if p.is_dir()
    )


# ---------------------------------------------------------------------------
# Manifest schema tests
# ---------------------------------------------------------------------------

def test_manifest_exists() -> None:
    """manifest.json must exist in the mirror root."""
    assert MANIFEST_PATH.exists(), (
        f"manifest.json not found at {MANIFEST_PATH} — "
        "run: python scripts/skills.py"
    )


def test_manifest_valid_json() -> None:
    """manifest.json must be valid JSON."""
    text = MANIFEST_PATH.read_text(encoding="utf-8")
    manifest = json.loads(text)  # raises on invalid JSON
    assert isinstance(manifest, dict)


def test_manifest_required_keys() -> None:
    """manifest.json must contain the required top-level keys."""
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    required = {"schema_version", "bundle_name", "bundle_version", "skills", "format"}
    missing = required - set(manifest)
    assert not missing, f"manifest.json missing required keys: {sorted(missing)}"


def test_manifest_schema_version() -> None:
    """schema_version must be '1.0'."""
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    assert manifest["schema_version"] == "1.0", (
        f"unexpected schema_version: {manifest['schema_version']!r}"
    )


def test_manifest_bundle_name() -> None:
    """bundle_name must be 'starboard'."""
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    assert manifest["bundle_name"] == "starboard"


def test_manifest_format_field() -> None:
    """format must be 'agent-skills'."""
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    assert manifest["format"] == "agent-skills"


def test_manifest_skills_count() -> None:
    """manifest.json must list exactly EXPECTED_SKILL_COUNT skills."""
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    skills = manifest.get("skills", [])
    assert isinstance(skills, list)
    assert len(skills) == EXPECTED_SKILL_COUNT, (
        f"expected {EXPECTED_SKILL_COUNT} skills in manifest, found {len(skills)}"
    )


def test_manifest_matches_canonical_roster() -> None:
    """Every canonical skill is in the manifest and no phantom entries exist."""
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    manifest_names = {s["name"] for s in manifest.get("skills", [])}
    canonical_names = set(_canonical_skill_names())
    missing = canonical_names - manifest_names
    extra = manifest_names - canonical_names
    assert not missing, f"skills missing from manifest: {sorted(missing)}"
    assert not extra, f"manifest has unknown skills (not in canonical tree): {sorted(extra)}"


def test_manifest_skill_entries_have_required_fields() -> None:
    """Each skill entry must have 'name', 'path', and 'description'."""
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    for skill in manifest.get("skills", []):
        name = skill.get("name", "<unknown>")
        assert "name" in skill, f"skill entry missing 'name': {skill}"
        assert "path" in skill, f"{name}: skill entry missing 'path'"
        assert "description" in skill, f"{name}: skill entry missing 'description'"
        # path must point to the skill subdirectory
        assert skill["path"] == f"{skill['name']}/", (
            f"{name}: 'path' should be '{skill['name']}/', got {skill['path']!r}"
        )


# ---------------------------------------------------------------------------
# Mirror structure tests
# ---------------------------------------------------------------------------

def test_mirror_directory_exists() -> None:
    """The mirror directory must exist."""
    assert MIRROR_ROOT.is_dir(), (
        f"aitools mirror not found at {MIRROR_ROOT} — "
        "run: python scripts/skills.py"
    )


def test_mirror_skill_count() -> None:
    """Mirror must contain exactly EXPECTED_SKILL_COUNT skill directories."""
    names = _mirror_skill_names()
    assert len(names) == EXPECTED_SKILL_COUNT, (
        f"expected {EXPECTED_SKILL_COUNT} skill dirs in mirror, found {len(names)}: {names}"
    )


def test_mirror_matches_canonical_roster() -> None:
    """Mirror skill directories must match the canonical roster exactly."""
    assert set(_mirror_skill_names()) == set(_canonical_skill_names()), (
        f"mirror dirs {set(_mirror_skill_names())} != "
        f"canonical dirs {set(_canonical_skill_names())}"
    )


@pytest.mark.parametrize("skill_dir_name", _canonical_skill_names())
def test_mirror_skill_has_skill_md(skill_dir_name: str) -> None:
    """Each mirrored skill directory must contain SKILL.md."""
    skill_md = MIRROR_ROOT / skill_dir_name / "SKILL.md"
    assert skill_md.exists(), f"{skill_dir_name}: SKILL.md missing in mirror"


# ---------------------------------------------------------------------------
# Frontmatter validation tests (Agent Skills spec + ai-dev-kit rules)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("skill_dir_name", _canonical_skill_names())
def test_mirror_frontmatter_name_valid(skill_dir_name: str) -> None:
    """name field: required, ≤64 chars, lowercase alnum+hyphens, no XML, matches dir."""
    skill_md = MIRROR_ROOT / skill_dir_name / "SKILL.md"
    fm = _parse_frontmatter(skill_md.read_text(encoding="utf-8"))
    name = fm.get("name")
    assert name, f"{skill_dir_name}: 'name' is required"
    name = str(name)
    assert len(name) <= NAME_MAX, f"{skill_dir_name}: name exceeds {NAME_MAX} chars"
    assert _NAME_RE.match(name), (
        f"{skill_dir_name}: name '{name}' must be lowercase alnum + single hyphens"
    )
    assert not _XML_TAG_RE.search(name), f"{skill_dir_name}: name must not contain XML tags"
    for word in _RESERVED_WORDS:
        assert word not in name, (
            f"{skill_dir_name}: name must not contain reserved word '{word}'"
        )
    assert name == skill_dir_name, (
        f"{skill_dir_name}: spec requires name == directory name (got '{name}')"
    )


@pytest.mark.parametrize("skill_dir_name", _canonical_skill_names())
def test_mirror_frontmatter_description_valid(skill_dir_name: str) -> None:
    """description field: required, non-empty, ≤1024 chars, no XML."""
    skill_md = MIRROR_ROOT / skill_dir_name / "SKILL.md"
    fm = _parse_frontmatter(skill_md.read_text(encoding="utf-8"))
    desc = fm.get("description")
    assert desc and str(desc).strip(), f"{skill_dir_name}: 'description' is required and non-empty"
    desc = str(desc)
    assert len(desc) <= DESCRIPTION_MAX, (
        f"{skill_dir_name}: description exceeds {DESCRIPTION_MAX} chars ({len(desc)})"
    )
    assert not _XML_TAG_RE.search(desc), (
        f"{skill_dir_name}: description must not contain XML tags"
    )


# ---------------------------------------------------------------------------
# Drift / stability tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("skill_dir_name", _canonical_skill_names())
def test_mirror_skill_files_match_canonical(skill_dir_name: str) -> None:
    """Each mirrored skill's files must be byte-identical to the canonical source.

    This is the per-skill stability check that detects when the canonical
    tree has changed but the mirror hasn't been regenerated.  The full
    regenerate-and-diff is in ``make test-distribution``; this parametrized
    form catches regressions at the per-skill level in ``make test-unit``.
    """
    canonical_dir = CANONICAL_SKILLS_ROOT / skill_dir_name
    mirror_dir = MIRROR_ROOT / skill_dir_name

    canonical_files = {
        p.relative_to(canonical_dir).as_posix()
        for p in canonical_dir.rglob("*")
        if p.is_file()
    }
    mirror_files = {
        p.relative_to(mirror_dir).as_posix()
        for p in mirror_dir.rglob("*")
        if p.is_file()
    }

    missing = canonical_files - mirror_files
    extra = mirror_files - canonical_files
    assert not missing, f"{skill_dir_name}: files missing from mirror: {sorted(missing)}"
    assert not extra, f"{skill_dir_name}: stale files in mirror: {sorted(extra)}"

    differing = {
        rel
        for rel in canonical_files & mirror_files
        if not filecmp.cmp(
            canonical_dir / rel, mirror_dir / rel, shallow=False
        )
    }
    assert not differing, (
        f"{skill_dir_name}: mirror files differ from canonical: {sorted(differing)}\n"
        "Run: python scripts/skills.py"
    )


# ---------------------------------------------------------------------------
# check() tolerates vendor()-preserved non-skill root files (drift-guard fix)
# ---------------------------------------------------------------------------

class TestCheckToleratesPreservedRootFiles:
    """`skills.check()` must agree with `skills.vendor()` on preserved files.

    vendor() (re)generates manifest.json and deliberately preserves any other
    top-level file in the mirror root; check() must therefore not report such a
    file as drift, while still catching real drift inside a skill directory.
    """

    @staticmethod
    def _load_skills_module():
        import importlib.util

        script = REPO_ROOT / "scripts" / "skills.py"
        spec = importlib.util.spec_from_file_location("skills_script_under_test", script)
        assert spec and spec.loader
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod

    @staticmethod
    def _setup(tmp_path: Path) -> tuple[Path, Path, Path]:
        skill_md = "---\nname: starboard-demo\ndescription: demo\n---\n\nBody.\n"
        canonical = tmp_path / "canonical"
        (canonical / "starboard-demo").mkdir(parents=True)
        (canonical / "starboard-demo" / "SKILL.md").write_text(skill_md)

        mirror = tmp_path / "mirror"
        (mirror / "starboard-demo").mkdir(parents=True)
        (mirror / "starboard-demo" / "SKILL.md").write_text(skill_md)
        manifest = mirror / "manifest.json"
        manifest.write_text(
            json.dumps(
                {
                    "schema_version": "1.0",
                    "bundle_name": "starboard",
                    "skills": [{"name": "starboard-demo", "path": "starboard-demo/"}],
                }
            )
        )
        return canonical, mirror, manifest

    def test_preserved_root_file_is_not_drift(self, tmp_path, monkeypatch) -> None:
        mod = self._load_skills_module()
        canonical, mirror, manifest = self._setup(tmp_path)
        (mirror / "README.md").write_text("# aitools bundle\n")  # vendor preserves this

        monkeypatch.setattr(mod, "CANONICAL_SKILLS", canonical)
        monkeypatch.setattr(mod, "MIRROR_ROOT", mirror)
        monkeypatch.setattr(mod, "MANIFEST_PATH", manifest)

        assert mod.check() == 0, "check() falsely flagged a preserved root file as drift"

    def test_stale_file_inside_skill_dir_is_still_drift(self, tmp_path, monkeypatch) -> None:
        mod = self._load_skills_module()
        canonical, mirror, manifest = self._setup(tmp_path)
        (mirror / "starboard-demo" / "STALE.md").write_text("stale\n")

        monkeypatch.setattr(mod, "CANONICAL_SKILLS", canonical)
        monkeypatch.setattr(mod, "MIRROR_ROOT", mirror)
        monkeypatch.setattr(mod, "MANIFEST_PATH", manifest)

        assert mod.check() == 1, "check() missed a genuinely stale skill file"
