/**
 * Advisor report bubble component.
 *
 * Specialized UI for performance optimization reports (query, job, table, compute agents).
 * Currently renders markdown format; will be enhanced with specialized components in future.
 */

"use client";

import React, { useMemo, useCallback } from "react";
import { Box, Paper, Typography } from "@mui/material";
import { useTheme } from "@mui/material/styles";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type {
  Message,
  AdvisorReport,
  NextStepOption,
  FeedbackRating,
  DataTable,
} from "@/lib/types/api";
import { MessageStatus } from "@/lib/types/api";
import { ReportHeader, ReportFooter, BudgetExhaustedAlert } from "../shared";
import { FeedbackWidget } from "../FeedbackWidget";
import { FindingCard } from "./FindingCard";
import { MarkdownCodeRenderer } from "../message-parts/MarkdownCodeRenderer";
import { RecommendationCard } from "./RecommendationCard";
import { DataTableView } from "./compute/DataTableView";
import { mapFindingsToRecommendations } from "@/lib/utils/report-mappers";
import { downloadMarkdown, downloadJson } from "@/lib/utils/file-download";
import { exportAdvisorReportToMarkdown, prepareReportForJsonExport } from "@/lib/utils/report-export";

/** Stable reference for ReactMarkdown components to prevent re-renders */
const MARKDOWN_COMPONENTS = { code: MarkdownCodeRenderer };

interface AdvisorReportBubbleProps {
  /** Message containing the advisor report */
  message: Message;
  /** Advisor report data */
  report: AdvisorReport;
  /** Next step selection handler */
  onSelectOption?: (option: NextStepOption) => void;
  /** Feedback submission handler */
  onSubmitFeedback?: (messageId: string, rating: FeedbackRating) => Promise<void>;
}

/**
 * Advisor report bubble component.
 *
 * Renders performance optimization reports with markdown formatting.
 * Future enhancements:
 * - SQL rewrite diff viewer
 * - Findings with impact/effort badges
 * - Spark UI integration
 *
 * @param props - Component props
 * @returns Advisor report bubble component
 *
 * @example
 * ```tsx
 * <AdvisorReportBubble
 *   message={message}
 *   report={advisorReport}
 *   onSelectOption={handleNextStep}
 *   onSubmitFeedback={handleFeedback}
 * />
 * ```
 */
export function AdvisorReportBubble({
  message,
  report,
  onSubmitFeedback,
}: Omit<AdvisorReportBubbleProps, 'onSelectOption'>) {
  const theme = useTheme();
  const [useEnhancedView, setUseEnhancedView] = React.useState(true);
  
  // Get display content from formatted_markdown (generated by backend)
  const formattedMarkdown = message.metadata?.formatted_markdown as string | undefined;
  
  // Extract Summary section (everything before "### Recommendations")
  // Note: Using report.summary?.overview as dependency per React Compiler inference
  const summaryContent = useMemo(() => {
    if (!formattedMarkdown) return report.summary?.overview || "";
    
    const recommendationsIndex = formattedMarkdown.indexOf("### Recommendations");
    if (recommendationsIndex !== -1) {
      return formattedMarkdown.substring(0, recommendationsIndex).trim();
    }
    return formattedMarkdown;
  }, [formattedMarkdown, report.summary?.overview]);
  
  // Extract Optimized Query section (everything from "### Optimized Query" onwards)
  const optimizedQueryContent = useMemo(() => {
    if (!formattedMarkdown) return "";
    
    const queryIndex = formattedMarkdown.indexOf("### Optimized Query");
    if (queryIndex !== -1) {
      return formattedMarkdown.substring(queryIndex);
    }
    return "";
  }, [formattedMarkdown]);
  
  // Transform findings to recommendations for enhanced view
  // Note: Using report.analysis as dependency per React Compiler inference
  const recommendations = useMemo(() => {
    if (report.analysis?.findings) {
      // Type assertion needed due to Finding type differences between generated and local types
      return mapFindingsToRecommendations(report.analysis.findings as unknown as Parameters<typeof mapFindingsToRecommendations>[0]);
    }
    return [];
  }, [report.analysis]);

  // Get stable timestamp once for use in downloads
  const reportTimestamp = useMemo(() => {
    return message.timestamp 
      ? new Date(message.timestamp).toISOString().split("T")[0]
      : new Date().toISOString().split("T")[0];
  }, [message.timestamp]);

  // Memoize download handlers to prevent child re-renders
  // BB-04: Generate comprehensive, visually stunning exports
  const handleDownloadMarkdown = useCallback(() => {
    // Use comprehensive markdown export utility
    const markdown = exportAdvisorReportToMarkdown({
      report,
      timestamp: message.timestamp,
    });
    downloadMarkdown(markdown, `advisor-report-${reportTimestamp}.md`);
  }, [report, message.timestamp, reportTimestamp]);

  const handleDownloadJSON = useCallback(() => {
    // Export complete report with metadata
    const exportData = prepareReportForJsonExport(
      message.metadata?.complete_report || report,
      {
        timestamp: message.timestamp,
        domain: report.report_type || "advisor",
        conversationId: message.conversation_id,
      }
    );
    downloadJson(exportData, `advisor-report-${reportTimestamp}.json`);
  }, [message.metadata, message.timestamp, message.conversation_id, report, reportTimestamp]);

  return (
    <Box
      sx={{
        display: "flex",
        justifyContent: "flex-start",
        mb: 2,
        px: 2,
      }}
    >
      <Box
        sx={{
          display: "flex",
          gap: 1,
          maxWidth: "85%",
          flexDirection: "row",
        }}
      >
        <Box sx={{ flex: 1, minWidth: 0 }}>
          <Paper
            elevation={2}
            sx={{
              p: 2,
              bgcolor:
                theme.palette.mode === "dark"
                  ? "rgba(76, 175, 80, 0.08)"
                  : "rgba(76, 175, 80, 0.04)",
              borderRadius: 2,
              borderLeft: `4px solid ${theme.palette.success.main}`,
            }}
          >
            {/* Header with download/share/re-run (Phase 2) */}
            <ReportHeader
              title="Performance Analysis"
              icon="🔧"
              onDownloadMarkdown={handleDownloadMarkdown}
              onDownloadJSON={handleDownloadJSON}
              hasCompleteReport={!!message.metadata?.complete_report}
              conversationId={message.conversation_id}
            />

            {/* Budget exhaustion warning */}
            {(report as AdvisorReport & { budget_exhausted?: boolean }).budget_exhausted && <BudgetExhaustedAlert />}

            {/* Markdown styling - shared across sections */}
            {(() => {
              const markdownStyles = {
                "& h1": {
                  fontSize: "1.5rem",
                  fontWeight: 700,
                  marginTop: 2,
                  marginBottom: 1.5,
                  color: "text.primary",
                  "&:first-of-type": { marginTop: 0 },
                },
                "& h2": {
                  fontSize: "1.25rem",
                  fontWeight: 600,
                  marginTop: 2,
                  marginBottom: 1,
                  color: "text.primary",
                  "&:first-of-type": { marginTop: 0 },
                },
                "& h3": {
                  fontSize: "1.1rem",
                  fontWeight: 600,
                  marginTop: 1.5,
                  marginBottom: 0.75,
                  color: "text.primary",
                },
                "& p": {
                  margin: 0,
                  marginBottom: 1,
                  lineHeight: 1.6,
                  "&:last-child": { marginBottom: 0 },
                },
                "& ul, & ol": {
                  margin: 0,
                  marginBottom: 1,
                  paddingLeft: 3,
                  "& li": {
                    marginBottom: 0.5,
                  },
                },
                "& strong": {
                  fontWeight: 600,
                  color: theme.palette.mode === "dark" ? "success.light" : "success.dark",
                },
                "& code": {
                  bgcolor:
                    theme.palette.mode === "dark"
                      ? "rgba(255, 255, 255, 0.1)"
                      : "rgba(0, 0, 0, 0.05)",
                  padding: "2px 6px",
                  borderRadius: 1,
                  fontSize: "0.9em",
                  fontFamily: "monospace",
                },
                "& pre": {
                  bgcolor:
                    theme.palette.mode === "dark"
                      ? "rgba(0, 0, 0, 0.3)"
                      : "rgba(0, 0, 0, 0.05)",
                  padding: 2,
                  borderRadius: 1,
                  overflow: "auto",
                  marginBottom: 1,
                  "& code": {
                    bgcolor: "transparent",
                    padding: 0,
                  },
                },
                "& hr": {
                  border: "none",
                  borderTop: `1px solid ${theme.palette.divider}`,
                  margin: "16px 0",
                },
              };

              return (
                <>
                  {/* 1. SUMMARY SECTION FIRST - from markdown */}
                  {summaryContent && (
                    <Box sx={{ ...markdownStyles, mb: 3 }}>
                      <ReactMarkdown 
                        remarkPlugins={[remarkGfm]}
                        components={MARKDOWN_COMPONENTS}
                      >
                        {summaryContent}
                      </ReactMarkdown>
                    </Box>
                  )}

                  {/* 1.5 DATA TABLE - for listing/enumeration requests */}
                  {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
                  {(report as any).data_table?.rows?.length > 0 && (
                    <Box sx={{ mb: 3 }}>
                      {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
                      <DataTableView table={(report as any).data_table as DataTable} />
                    </Box>
                  )}

                  {/* 2. RECOMMENDATIONS SECTION - structured UI */}
                  {report.analysis?.findings && report.analysis.findings.length > 0 && (
                    <Box sx={{ mb: 3 }}>
                      {useEnhancedView && recommendations.length > 0 ? (
                        /* Enhanced View: Recommendations with Impact/Effort Badges */
                        <Box>
                          <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", mb: 2 }}>
                            <Typography
                              variant="h6"
                              sx={{
                                fontWeight: 600,
                                display: "flex",
                                alignItems: "center",
                                gap: 1,
                              }}
                            >
                              📋 Recommendations ({recommendations.length})
                            </Typography>
                            <Typography
                              variant="caption"
                              sx={{
                                color: "text.secondary",
                                cursor: "pointer",
                                textDecoration: "underline",
                                "&:hover": { color: "primary.main" },
                              }}
                              onClick={() => setUseEnhancedView(false)}
                            >
                              Switch to detailed view
                            </Typography>
                          </Box>
                          {recommendations.map((rec, index) => (
                            <RecommendationCard
                              key={rec.id}
                              item={rec}
                              index={index + 1}
                              defaultExpanded={index === 0}
                              onApply={() => {
                                // TODO(BACKLOG-010): Implement recommendation apply handler
                              }}
                            />
                          ))}
                        </Box>
                      ) : (
                        /* Standard View: Detailed Findings */
                        <Box>
                          <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", mb: 2 }}>
                            <Typography
                              variant="h6"
                              sx={{
                                fontWeight: 600,
                                display: "flex",
                                alignItems: "center",
                                gap: 1,
                              }}
                            >
                              📋 Optimization Findings ({report.analysis.findings.length})
                            </Typography>
                            {recommendations.length > 0 && (
                              <Typography
                                variant="caption"
                                sx={{
                                  color: "text.secondary",
                                  cursor: "pointer",
                                  textDecoration: "underline",
                                  "&:hover": { color: "primary.main" },
                                }}
                                onClick={() => setUseEnhancedView(true)}
                              >
                                Switch to enhanced view
                              </Typography>
                            )}
                          </Box>
                          {report.analysis.findings.map((finding, index) => (
                            <FindingCard
                              key={finding.id || index}
                              finding={finding}
                              index={index}
                              onAction={() => {
                                // TODO(BACKLOG-011): Implement finding action handlers (mark applied, explain more)
                              }}
                              defaultExpanded={index === 0} // First finding expanded by default
                            />
                          ))}
                        </Box>
                      )}
                    </Box>
                  )}

                  {/* 3. OPTIMIZED QUERY SECTION - from markdown (if present) */}
                  {optimizedQueryContent && (
                    <Box sx={markdownStyles}>
                      <ReactMarkdown 
                        remarkPlugins={[remarkGfm]}
                        components={MARKDOWN_COMPONENTS}
                      >
                        {optimizedQueryContent}
                      </ReactMarkdown>
                    </Box>
                  )}
                </>
              );
            })()}

            {/* Footer with metadata */}
            <ReportFooter metadata={message.metadata} />
          </Paper>

          {/* Timestamp */}
          {message.timestamp && (
            <Box sx={{ display: "flex", mt: 0.5, px: 1 }}>
              <Typography variant="caption" color="text.secondary">
                {new Date(message.timestamp).toLocaleTimeString([], {
                  hour: "2-digit",
                  minute: "2-digit",
                })}
              </Typography>
            </Box>
          )}

          {/* Next Steps are now rendered separately by MessageList (Phase 2) */}

          {/* Feedback Widget */}
          {message.status === MessageStatus.COMPLETED &&
            onSubmitFeedback &&
            !message.next_steps?.length && (
              <Box
                sx={{
                  display: "flex",
                  justifyContent: "flex-end",
                  mt: 1,
                  px: 1,
                }}
              >
                <FeedbackWidget
                  messageId={message.message_id || message.id}
                  conversationId={message.conversation_id}
                  onSubmitFeedback={onSubmitFeedback}
                  disabled={false}
                />
              </Box>
            )}
        </Box>
      </Box>
    </Box>
  );
}

