"""Isaac/Codex rules deployment backend for starboard-maint."""
from __future__ import annotations

import shutil
from pathlib import Path

_ALL_DOMAINS = ["baseline", "jobs", "sql", "warehouse", "uc", "cluster", "discovery"]


def _rule_filename(domain: str) -> str:
    return f"starboard-{domain}.md"


def install(
    rules_src: Path,
    rules_dest: Path,
    domains: list[str] | None = None,
) -> dict[str, object]:
    """Copy per-domain ruleset files from *rules_src* to *rules_dest*.

    *domains* defaults to all available domains.
    Returns extra fields to record in maint.json.
    """
    if not rules_src.is_dir():
        raise FileNotFoundError(f"Rules source directory not found: {rules_src}")

    requested = domains if domains is not None else _ALL_DOMAINS
    rules_dest.mkdir(parents=True, exist_ok=True)

    deployed: list[str] = []
    missing: list[str] = []
    for domain in requested:
        filename = _rule_filename(domain)
        src_file = rules_src / filename
        if src_file.is_file():
            shutil.copy2(src_file, rules_dest / filename)
            deployed.append(domain)
        else:
            missing.append(domain)

    if missing:
        # Non-fatal: some rulesets may not exist yet (generated by X7).
        pass

    return {
        "rules_path": str(rules_dest),
        "deployed_domains": deployed,
        "missing_domains": missing,
    }


def remove(rules_dest: Path, domains: list[str] | None = None) -> None:
    """Remove deployed ruleset files from *rules_dest*."""
    requested = domains if domains is not None else _ALL_DOMAINS
    for domain in requested:
        target = rules_dest / _rule_filename(domain)
        if target.is_file():
            target.unlink()


def verify(
    rules_src: Path,
    rules_dest: Path,
    domains: list[str] | None = None,
) -> tuple[bool, str]:
    """Check that deployed rulesets exist and match the source.

    Returns ``(ok, message)``.
    """
    requested = domains if domains is not None else _ALL_DOMAINS
    missing: list[str] = []
    drifted: list[str] = []

    for domain in requested:
        filename = _rule_filename(domain)
        src_file = rules_src / filename
        if not src_file.is_file():
            # Source doesn't exist — skip (X7 not yet run).
            continue
        dest_file = rules_dest / filename
        if not dest_file.is_file():
            missing.append(domain)
        elif src_file.read_bytes() != dest_file.read_bytes():
            drifted.append(domain)

    if missing or drifted:
        parts = []
        if missing:
            parts.append(f"not deployed: {missing}")
        if drifted:
            parts.append(f"drift: {drifted}")
        return False, "Rules out of sync — " + "; ".join(parts)

    return True, f"OK: rules in sync at {rules_dest}"
