# Copyright (c) 2025 Databricks, Inc.
# Licensed under the Databricks Open Model License. See LICENSE for the full text.
"""Generate the agent-experience capability catalog from live sources (Task E2, D-3.1).

Usage::

    python scripts/gen_catalog.py           # generate the catalog + per-surface index pages
    python scripts/gen_catalog.py --check    # exit 1 if any committed page is stale

Output
------
``docs/reference/CATALOG.md`` — the top-level capability index, plus one
``INDEX.md`` per surface under ``docs/reference/{skills,mcp-tools,agents,
cli-commands,progressive-helpers,plugins}/``.

Why generate
------------
The *surface lists* (which skills/tools/agents/CLI-commands/helpers/plugins
exist) are read from the live sources so they can never drift from the shipped
code (D-3.1). Hand-authored prose (the "how to choose" guide, hero workflows)
lives in separate, non-generated files.

Live sources
------------
- MCP tools     — ``ALL_TOOL_METADATA`` in ``starboard.agents.tools.registry``.
                  The authoritative tool count is ``len(ALL_TOOL_METADATA)``
                  (D-3.2). Tools are *shared* across agents; the catalog states
                  the registry count and never publishes the inflated
                  per-agent sum.
- Skills        — ``packages/starboard-skills/skills/starboard/*/SKILL.md``.
- Agents        — ``packages/starboard-skills/agents/*.yaml``.
- CLI commands  — the routed command groups in ``starboard.cli.cli.main`` /
                  ``review_command`` / ``auth_commands``.
- Helpers       — ``starboard_x.__main__._IMPLEMENTED`` / ``_DECLARED``
                  (``python -m starboard_x.<cap>``).
- Plugins       — the ``starboard.mcp_tools`` entry-point contract + the sample
                  plugin package.

Every generated page starts with a ``GENERATED`` marker comment so the source
of truth is unambiguous.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from importlib import import_module
from pathlib import Path

# ---------------------------------------------------------------------------
# Repo-root resolution (walk up until the canonical skills package is found)
# ---------------------------------------------------------------------------


def _repo_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "packages" / "starboard-skills" / "skills").is_dir():
            return parent
    raise AssertionError("Cannot locate repo root (expected packages/starboard-skills/skills/)")


REPO_ROOT = _repo_root()
SKILLS_ROOT = REPO_ROOT / "packages" / "starboard-skills" / "skills" / "starboard"
AGENTS_ROOT = REPO_ROOT / "packages" / "starboard-skills" / "agents"
REFERENCE_DIR = REPO_ROOT / "docs" / "reference"

GENERATED_MARKER = (
    "<!-- GENERATED by scripts/gen_catalog.py — DO NOT EDIT. "
    "Regenerate: python scripts/gen_catalog.py -->"
)

# Per-surface index pages, keyed by the sub-directory under docs/reference/.
SURFACES: tuple[str, ...] = (
    "skills",
    "mcp-tools",
    "agents",
    "cli-commands",
    "progressive-helpers",
    "plugins",
)

# ---------------------------------------------------------------------------
# Markdown-cell sanitisation
# ---------------------------------------------------------------------------

_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)


def _cell(text: str) -> str:
    """Sanitise *text* for use inside a single Markdown table cell.

    Keeps only the first non-empty line, escapes pipes (which would otherwise
    split the cell), collapses whitespace, and neutralises Jinja delimiters so
    the mkdocs-macros plugin cannot try to render registry-supplied prose.
    """
    first = ""
    for line in text.splitlines():
        if line.strip():
            first = line.strip()
            break
    first = re.sub(r"\s+", " ", first)
    first = first.replace("|", r"\|")
    first = first.replace("{{", "{ {").replace("}}", "} }")
    first = first.replace("{%", "{ %").replace("%}", "% }")
    return first


def _read_frontmatter(md_path: Path) -> dict[str, object]:
    """Return the parsed YAML frontmatter of a Markdown file (empty on miss)."""
    import yaml

    text = md_path.read_text(encoding="utf-8")
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return {}
    return yaml.safe_load(m.group(1)) or {}


# ---------------------------------------------------------------------------
# Surface collectors — each reads a live source and returns sorted entries
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SkillEntry:
    name: str
    description: str
    directory: str


@dataclass(frozen=True)
class ToolEntry:
    name: str
    summary: str
    required: tuple[str, ...]


@dataclass(frozen=True)
class AgentEntry:
    name: str
    kind: str
    domain: str
    mcp_tool: str
    skill_ref: str
    description: str


@dataclass(frozen=True)
class CliEntry:
    command: str
    purpose: str
    invocation: str
    dispatch: str  # importable "module:symbol" that routes the command


@dataclass(frozen=True)
class HelperEntry:
    name: str
    invocation: str
    implemented: bool
    module: str


@dataclass(frozen=True)
class PluginEntry:
    entry_point_group: str
    sample_package: str
    contract: str


def collect_skills() -> list[SkillEntry]:
    """Read every ``SKILL.md`` under the canonical skills tree."""
    entries: list[SkillEntry] = []
    for skill_md in sorted(SKILLS_ROOT.glob("*/SKILL.md")):
        fm = _read_frontmatter(skill_md)
        entries.append(
            SkillEntry(
                name=str(fm.get("name", skill_md.parent.name)),
                description=str(fm.get("description", "")),
                directory=skill_md.parent.name,
            )
        )
    return sorted(entries, key=lambda e: e.name)


def collect_tools() -> list[ToolEntry]:
    """Read the live MCP-tool registry (``ALL_TOOL_METADATA``)."""
    registry = import_module("starboard.agents.tools.registry")
    all_meta: dict[str, dict[str, object]] = registry.ALL_TOOL_METADATA
    entries: list[ToolEntry] = []
    for name, meta in all_meta.items():
        params = meta.get("parameters") or {}
        required = params.get("required", []) if isinstance(params, dict) else []
        entries.append(
            ToolEntry(
                name=name,
                summary=str(meta.get("description", "")),
                required=tuple(str(r) for r in required),
            )
        )
    return sorted(entries, key=lambda e: e.name)


def collect_agents() -> list[AgentEntry]:
    """Read every canonical agent definition (``agents/*.yaml``)."""
    import yaml

    entries: list[AgentEntry] = []
    for yaml_path in sorted(AGENTS_ROOT.glob("*.yaml")):
        data = yaml.safe_load(yaml_path.read_text(encoding="utf-8")) or {}
        entries.append(
            AgentEntry(
                name=str(data.get("name", yaml_path.stem)),
                kind=str(data.get("kind", "")),
                domain=str(data.get("domain", "")),
                mcp_tool=str(data.get("mcp_tool") or "—"),
                skill_ref=str(data.get("skill_ref", "")),
                description=str(data.get("description", "")),
            )
        )
    return sorted(entries, key=lambda e: e.name)


def collect_cli_commands() -> list[CliEntry]:
    """Enumerate the CLI command surface.

    Each entry names the importable dispatch symbol that routes the command in
    ``starboard.cli.cli.main.main``; :func:`_verify_cli_dispatch` imports them
    so a renamed/removed route fails generation instead of drifting silently.
    """
    return [
        CliEntry(
            command="starboard --goal / --chat",
            purpose="Natural-language goal agent (multi-agent loop) and interactive chat.",
            invocation='starboard --goal "<request>"  ·  starboard --chat',
            dispatch="starboard.cli.cli.main:parse_args",
        ),
        CliEntry(
            command="starboard --discover",
            purpose="Non-agentic workspace discovery and health assessment.",
            invocation="starboard --discover",
            dispatch="starboard.cli.cli.main:run_discovery_mode",
        ),
        CliEntry(
            command="starboard review",
            purpose="Workload Review over public system.* data (severity gate).",
            invocation="starboard review [--domains jobs,sql,warehouse]",
            dispatch="starboard.cli.cli.review_command:run_review",
        ),
        CliEntry(
            command="starboard auth",
            purpose="Auth-by-subtraction helpers (login / status) over the SDK credential chain.",
            invocation="starboard auth login  ·  starboard auth status",
            dispatch="starboard.cli.cli.auth_commands:run_auth",
        ),
    ]


def collect_helpers() -> list[HelperEntry]:
    """Read the live progressive-helper dispatch table from ``starboard_x``."""
    dispatcher = import_module("starboard_x.__main__")
    implemented: dict[str, str] = dict(dispatcher._IMPLEMENTED)
    declared: tuple[str, ...] = tuple(dispatcher._DECLARED)
    entries: list[HelperEntry] = []
    for name, module in implemented.items():
        entries.append(
            HelperEntry(
                name=name,
                invocation=f"python -m starboard_x.{name}",
                implemented=True,
                module=module.rsplit(".", 1)[0],
            )
        )
    for name in declared:
        entries.append(
            HelperEntry(
                name=name,
                invocation=f"python -m starboard_x.{name}",
                implemented=False,
                module=f"starboard_x.{name}",
            )
        )
    return sorted(entries, key=lambda e: e.name)


def collect_plugins() -> PluginEntry:
    """Describe the opt-in per-domain plugin contract + the sample package."""
    return PluginEntry(
        entry_point_group="starboard.mcp_tools",
        sample_package="starboard-plugin-sample",
        contract="starboard.tools.plugins.ToolPlugin",
    )


# ---------------------------------------------------------------------------
# Dispatch verification (fail generation on a dead CLI route)
# ---------------------------------------------------------------------------


def _verify_cli_dispatch(entries: list[CliEntry]) -> None:
    for entry in entries:
        module_name, _, symbol = entry.dispatch.partition(":")
        module = import_module(module_name)
        if not hasattr(module, symbol):
            raise AssertionError(
                f"CLI dispatch symbol not found: {entry.dispatch} "
                f"(command {entry.command!r})"
            )


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

_TIER_NOTE = (
    "> **Dollar figures are list-price DBU estimates** — always labelled as such.\n"
    "> This catalog is generated from live sources; see "
    "[How to choose](../../guides/AGENT_EXPERIENCE.md) for the tier model."
)


def _header(title: str, blurb: str, up: str = "../CATALOG.md") -> str:
    return (
        f"{GENERATED_MARKER}\n\n"
        f"# {title}\n\n"
        f"{blurb}\n\n"
        f"[← Capability Catalog]({up})\n"
    )


def render_skills(entries: list[SkillEntry]) -> str:
    rows = "\n".join(
        f"| `{e.name}` | {_cell(e.description)} | Claude Code · Cursor · Claude Desktop · Genie |"
        for e in entries
    )
    return (
        _header(
            "Skills",
            f"**{len(entries)} skills.** Natural-language capabilities packaged as "
            "`SKILL.md` prompts; each maps to a domain agent and degrades to the "
            "`starboard-helper` CLI when MCP tools are absent.",
        )
        + "\n"
        "| Skill | Purpose | Hosts |\n"
        "|-------|---------|-------|\n"
        f"{rows}\n\n"
        "**Invocation:** trigger by intent in a skill-aware host (Claude Code / "
        "Cursor / Claude Desktop), or run the mirrored agent directly. "
        "**Inputs/outputs:** each skill takes a natural-language request plus "
        "optional identifiers (query/job/table/cluster/warehouse ids) and returns "
        "a prioritized advisor report. Source: "
        "`packages/starboard-skills/skills/starboard/<skill>/SKILL.md`.\n"
    )


def render_tools(entries: list[ToolEntry]) -> str:
    rows = "\n".join(
        f"| `{e.name}` | {_cell(e.summary)} | "
        f"{', '.join(f'`{r}`' for r in e.required) if e.required else '—'} |"
        for e in entries
    )
    return (
        _header(
            "MCP Tools",
            f"**{len(entries)} tools** in the shared registry "
            "(`len(ALL_TOOL_METADATA)`). Tools are **shared across agents** — this "
            "is the authoritative registry count, not a per-agent sum. Each tool is "
            "callable over MCP by name.",
        )
        + "\n"
        "**Invocation (example):**\n\n"
        "```python\n"
        'result = await client.call_tool("resolve_query", {"target": "<statement_id-or-sql>"})\n'
        "```\n\n"
        "| Tool | Purpose | Required inputs |\n"
        "|------|---------|-----------------|\n"
        f"{rows}\n\n"
        "**Outputs:** each tool returns a structured `dict` envelope. "
        "Source: `starboard.agents.tools.registry.ALL_TOOL_METADATA`.\n"
    )


def render_agents(entries: list[AgentEntry]) -> str:
    rows = "\n".join(
        f"| `{e.name}` | {e.kind} | {e.domain or '—'} | "
        f"{'`' + e.mcp_tool + '`' if e.mcp_tool != '—' else '—'} | `{e.skill_ref}` |"
        for e in entries
    )
    return (
        _header(
            "Agents",
            f"**{len(entries)} canonical agent definitions** "
            "(`packages/starboard-skills/agents/*.yaml`). Subagents are reached "
            "through their `mcp__starboard__*` tool; orchestrator and autonomous "
            "variants coordinate or run unattended. Prose docs for the core domain "
            "agents live under [Agents → Domain Agents](../../agents/README.md).",
        )
        + "\n"
        "| Agent | Kind | Domain | MCP invocation | Skill |\n"
        "|-------|------|--------|----------------|-------|\n"
        f"{rows}\n\n"
        "**Inputs/outputs:** an agent takes the domain target (id or NL request) "
        "and returns a prioritized, evidence-cited report. "
        "Source: `packages/starboard-skills/agents/<agent>.yaml`.\n"
    )


def render_cli(entries: list[CliEntry]) -> str:
    rows = "\n".join(
        f"| `{e.command}` | {e.purpose} | `{_cell(e.invocation)}` |" for e in entries
    )
    return (
        _header(
            "CLI Commands",
            f"**{len(entries)} command surfaces** exposed by the `starboard` CLI. "
            "The root command is the natural-language goal agent; `review` "
            "and `auth` are routed command groups.",
        )
        + "\n"
        "| Command | Purpose | Invocation |\n"
        "|---------|---------|------------|\n"
        f"{rows}\n\n"
        "**Inputs/outputs:** commands read flags/args and Databricks auth from the "
        "resolved credential chain (`--profile` / ambient); they print reports or "
        "JSON envelopes and use standard exit codes (`0` ok · `1` auth · `2` "
        "not-found · `3` api-error · `4` arg-error). Entry point: "
        "`starboard.cli.main:main`.\n"
    )


def render_helpers(entries: list[HelperEntry]) -> str:
    impl = [e for e in entries if e.implemented]
    decl = [e for e in entries if not e.implemented]
    impl_rows = "\n".join(
        f"| `{e.name}` | `{e.invocation}` | shipped |" for e in impl
    )
    decl_rows = "\n".join(
        f"| `{e.name}` | `{e.invocation}` | declared (lands in a later release) |"
        for e in decl
    )
    body = (
        "| Helper | Invocation | Status |\n"
        "|--------|------------|--------|\n"
        f"{impl_rows}\n"
    )
    if decl_rows:
        body += f"{decl_rows}\n"
    return (
        _header(
            "Progressive Helpers",
            f"**{len(impl)} shipped** progressive helpers (plus "
            f"{len(decl)} declared) in the capability tier — dependency-light "
            "`python -m starboard_x.<capability>` modules that run pure analyzers "
            "without the full experience wheel.",
        )
        + "\n"
        f"{body}\n"
        "**Inputs/outputs:** each helper reads a subcommand + options and emits a "
        "JSON envelope (`{ok, domain, command, data|error, meta}`). "
        "Source: `packages/starboard-core/starboard_x/`.\n"
    )


def render_plugins(plugin: PluginEntry) -> str:
    return (
        _header(
            "Plugins",
            "Opt-in per-domain **tool plugins** register through the public "
            f"`{plugin.entry_point_group}` entry-point group and are discovered at "
            "runtime. With no plugins installed, discovery returns an empty catalog "
            "and every built-in tool keeps working.",
        )
        + "\n"
        "| Aspect | Value |\n"
        "|--------|-------|\n"
        f"| Entry-point group | `{plugin.entry_point_group}` |\n"
        f"| Contract | `{plugin.contract}` |\n"
        f"| Reference package | `{plugin.sample_package}` |\n\n"
        "**Contract:** each entry-point value resolves to a `ToolPlugin` object; "
        "discovery loads it and registers its tools into a `ToolCatalog` keyed by "
        "the plugin's `name`. Copy `packages/starboard-plugin-sample/` as the "
        "starting point for a real per-domain plugin.\n"
    )


def render_catalog(
    skills: list[SkillEntry],
    tools: list[ToolEntry],
    agents: list[AgentEntry],
    cli: list[CliEntry],
    helpers: list[HelperEntry],
) -> str:
    n_helpers_impl = sum(1 for h in helpers if h.implemented)
    return (
        f"{GENERATED_MARKER}\n\n"
        "# Capability Catalog\n\n"
        "The single, generated index of every Starboard capability surface: skills, "
        "MCP tools, agents, CLI commands, progressive helpers, and plugins. The "
        "surface lists are generated from live sources by "
        "`scripts/gen_catalog.py`, so they cannot drift from the shipped code.\n\n"
        f"{_TIER_NOTE.replace('../../guides', '../guides')}\n\n"
        "## Surfaces\n\n"
        "| Surface | Count | What it is | Index |\n"
        "|---------|-------|------------|-------|\n"
        f"| Skills | {len(skills)} | NL capabilities as `SKILL.md` prompts | "
        "[skills](skills/INDEX.md) |\n"
        f"| MCP tools | {len(tools)} | Shared tool registry (callable over MCP) | "
        "[mcp-tools](mcp-tools/INDEX.md) |\n"
        f"| Agents | {len(agents)} | Canonical agent definitions | "
        "[agents](agents/INDEX.md) |\n"
        f"| CLI commands | {len(cli)} | `starboard` command surfaces | "
        "[cli-commands](cli-commands/INDEX.md) |\n"
        f"| Progressive helpers | {n_helpers_impl} | `python -m starboard_x.<cap>` | "
        "[progressive-helpers](progressive-helpers/INDEX.md) |\n"
        "| Plugins | contract | Opt-in per-domain tool plugins | "
        "[plugins](plugins/INDEX.md) |\n\n"
        "## Tool count\n\n"
        f"The authoritative MCP-tool count is **{len(tools)}** "
        "(`len(ALL_TOOL_METADATA)`). Tools are **shared across agents**, so a "
        "per-agent sum over-counts; this catalog always reports the registry "
        "count.\n\n"
        "## Choosing a surface\n\n"
        "See [How to choose: skill vs tool vs agent vs helper]"
        "(../guides/AGENT_EXPERIENCE.md) for the tier model and decision guide.\n"
    )


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


@dataclass
class RenderedPage:
    path: Path
    content: str


def build_pages() -> list[RenderedPage]:
    """Collect every live surface and render all catalog pages."""
    skills = collect_skills()
    tools = collect_tools()
    agents = collect_agents()
    cli = collect_cli_commands()
    helpers = collect_helpers()
    plugin = collect_plugins()

    _verify_cli_dispatch(cli)

    return [
        RenderedPage(REFERENCE_DIR / "CATALOG.md", render_catalog(skills, tools, agents, cli, helpers)),
        RenderedPage(REFERENCE_DIR / "skills" / "INDEX.md", render_skills(skills)),
        RenderedPage(REFERENCE_DIR / "mcp-tools" / "INDEX.md", render_tools(tools)),
        RenderedPage(REFERENCE_DIR / "agents" / "INDEX.md", render_agents(agents)),
        RenderedPage(REFERENCE_DIR / "cli-commands" / "INDEX.md", render_cli(cli)),
        RenderedPage(REFERENCE_DIR / "progressive-helpers" / "INDEX.md", render_helpers(helpers)),
        RenderedPage(REFERENCE_DIR / "plugins" / "INDEX.md", render_plugins(plugin)),
    ]


def generate_all(check: bool = False) -> bool:
    """Generate (or check) all catalog pages.

    Returns True when up-to-date/written; False (with a diff summary printed)
    when *check* is True and any committed page is stale.
    """
    pages = build_pages()
    stale: list[str] = []

    for page in pages:
        rel = page.path.relative_to(REPO_ROOT)
        if check:
            existing = page.path.read_text(encoding="utf-8") if page.path.exists() else ""
            if existing != page.content:
                stale.append(str(rel))
        else:
            page.path.parent.mkdir(parents=True, exist_ok=True)
            page.path.write_text(page.content, encoding="utf-8")
            print(f"  wrote {rel}")

    if check and stale:
        print("Stale catalog pages (run `python scripts/gen_catalog.py` to regenerate):")
        for p in stale:
            print(f"  {p}")
        return False

    if not check:
        print(f"Generated {len(pages)} catalog pages in {REFERENCE_DIR.relative_to(REPO_ROOT)}/")
    return True


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    if "-h" in args or "--help" in args:
        print(__doc__)
        return 0
    check = "--check" in args
    ok = generate_all(check=check)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
