#!/usr/bin/env python3
"""
Generate TypeScript types and Zod schemas from Pydantic models.

This script parses Pydantic models from the backend and generates:
1. TypeScript interfaces (for static type checking)
2. Zod schemas (for runtime validation)

The generated files replace manually maintained schemas, ensuring
backend and frontend stay in sync automatically.

IMPORTANT: Some types referenced by generated code are frontend-only
(e.g., ToolCall, CodeLineRef, ReferenceMaterial, TopContributor).
These are defined in:
- frontend/lib/types/extended-api.ts (TypeScript interfaces)
- frontend/lib/validation/extended-schemas.ts (Zod schemas)

The generated files automatically import from extended-schemas.ts
to resolve these dependencies.

Usage:
    python scripts/generate_types.py

Output:
    - frontend/lib/types/generated-api.ts (TypeScript interfaces)
    - frontend/lib/validation/generated-schemas.ts (Zod schemas)
"""

from __future__ import annotations

import inspect
import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, Literal, get_args, get_origin

# Add packages to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "packages" / "starboard-server"))

from pydantic import BaseModel  # noqa: E402
from pydantic.fields import FieldInfo  # noqa: E402


@dataclass
class TypeMapping:
    """Maps Python/Pydantic types to TypeScript and Zod equivalents."""

    python_type: str
    typescript_type: str
    zod_type: str


# Type mapping table
TYPE_MAPPINGS: dict[str, TypeMapping] = {
    "str": TypeMapping("str", "string", "z.string()"),
    "int": TypeMapping("int", "number", "z.number().int()"),
    "float": TypeMapping("float", "number", "z.number()"),
    "bool": TypeMapping("bool", "boolean", "z.boolean()"),
    "dict": TypeMapping("dict", "Record<string, any>", "z.record(z.string(), z.any())"),
    "list": TypeMapping("list", "Array<any>", "z.array(z.any())"),
    "Any": TypeMapping("Any", "any", "z.any()"),
    "datetime": TypeMapping("datetime", "string", "z.string().datetime()"),
}


@dataclass
class EnumDef:
    """Definition of an enum for code generation."""

    name: str
    values: dict[str, str]  # name -> value
    docstring: str | None


@dataclass
class FieldDef:
    """Definition of a model field for code generation."""

    name: str
    python_type: str
    typescript_type: str
    zod_type: str
    required: bool
    default: Any | None
    description: str | None
    validators: list[str]  # Zod validator methods (e.g., ".min(1)", ".max(100)")


@dataclass
class ModelDef:
    """Definition of a Pydantic model for code generation."""

    name: str
    fields: list[FieldDef]
    docstring: str | None
    base_class: str | None


class TypeGenerator:
    """Generates TypeScript types and Zod schemas from Pydantic models."""

    # Types that are referenced by generated code but defined in frontend extensions
    # These are imported from extended-schemas.ts / extended-api.ts
    # NOTE: Only truly frontend-only types should be here. Backend types should
    # be imported and generated by this script.
    FRONTEND_ONLY_TYPES: set[str] = {
        "ToolCall",  # Frontend-only: used for UI tool execution display
    }

    def __init__(self):
        self.enums: list[EnumDef] = []
        self.models: list[ModelDef] = []
        self.referenced_frontend_types: set[str] = set()

    def python_type_to_typescript(self, py_type: Any) -> str:
        """Convert Python type to TypeScript type string."""
        # Handle NoneType
        if py_type is type(None):
            return "null"

        # Handle Union types (e.g., str | None)
        origin = get_origin(py_type)

        # Handle Literal types (e.g., Literal["advisor"])
        if origin is Literal:
            args = get_args(py_type)
            # Convert each literal value to TypeScript
            ts_literals = [
                f'"{arg}"' if isinstance(arg, str) else str(arg) for arg in args
            ]
            return " | ".join(ts_literals)

        if origin is None:
            # Simple type
            type_name = (
                py_type.__name__ if hasattr(py_type, "__name__") else str(py_type)
            )
            if type_name in TYPE_MAPPINGS:
                return TYPE_MAPPINGS[type_name].typescript_type
            # Check if it's an enum
            if inspect.isclass(py_type) and issubclass(py_type, Enum):
                return py_type.__name__
            # Track frontend-only types that are referenced
            if type_name in self.FRONTEND_ONLY_TYPES:
                self.referenced_frontend_types.add(type_name)
            # Assume it's a model reference
            return type_name

        # Handle Union (e.g., str | None)
        if hasattr(origin, "__name__") and origin.__name__ == "UnionType":
            args = get_args(py_type)
            ts_types = [self.python_type_to_typescript(arg) for arg in args]
            return " | ".join(ts_types)

        # Handle List/Array
        if origin in (list, tuple):
            args = get_args(py_type)
            if args:
                item_type = self.python_type_to_typescript(args[0])
                return f"Array<{item_type}>"
            return "Array<any>"

        # Handle Dict/Record
        if origin is dict:
            args = get_args(py_type)
            if len(args) == 2:
                key_type = self.python_type_to_typescript(args[0])
                val_type = self.python_type_to_typescript(args[1])
                return f"Record<{key_type}, {val_type}>"
            return "Record<string, any>"

        # Fallback
        return "any"

    def python_type_to_zod(
        self, py_type: Any, field_info: FieldInfo | None = None
    ) -> tuple[str, list[str]]:
        """
        Convert Python type to Zod schema string and validators.

        Returns:
            (zod_base, validators) - Base zod type and list of validator methods
        """
        validators = []

        # Handle Union types (e.g., str | None)
        origin = get_origin(py_type)

        # Handle Literal types (e.g., Literal["advisor"])
        if origin is Literal:
            args = get_args(py_type)
            # Convert to z.literal() for single values or z.enum() for multiple
            if len(args) == 1:
                val = args[0]
                if isinstance(val, str):
                    return f'z.literal("{val}")', validators
                else:
                    return f"z.literal({val})", validators
            else:
                # Multiple literal values - use z.enum()
                enum_values = [
                    f'"{arg}"' if isinstance(arg, str) else str(arg) for arg in args
                ]
                return f"z.enum([{', '.join(enum_values)}])", validators

        if origin is None:
            # Simple type
            type_name = (
                py_type.__name__ if hasattr(py_type, "__name__") else str(py_type)
            )
            if type_name in TYPE_MAPPINGS:
                zod_base = TYPE_MAPPINGS[type_name].zod_type
            elif inspect.isclass(py_type) and issubclass(py_type, Enum):
                # Enum - generate z.enum() with values
                enum_values = [f'"{v.value}"' for v in py_type]
                zod_base = f"z.enum([{', '.join(enum_values)}])"
            else:
                # Model reference - use schema name
                # Track frontend-only types that are referenced
                if type_name in self.FRONTEND_ONLY_TYPES:
                    self.referenced_frontend_types.add(type_name)
                zod_base = f"{type_name}Schema"
        else:
            # Handle Union/Optional
            if hasattr(origin, "__name__") and origin.__name__ == "UnionType":
                args = get_args(py_type)
                # Check if it's Optional (Union with None)
                if type(None) in args:
                    non_none_args = [arg for arg in args if arg is not type(None)]
                    if len(non_none_args) == 1:
                        # Optional type
                        base, base_validators = self.python_type_to_zod(
                            non_none_args[0], field_info
                        )
                        validators.extend(base_validators)
                        validators.append(".nullable().optional()")
                        return base, validators
                    else:
                        # Union with multiple types + None
                        zod_types = [
                            self.python_type_to_zod(arg, None)[0]
                            for arg in non_none_args
                        ]
                        zod_base = f"z.union([{', '.join(zod_types)}])"
                        validators.append(".nullable().optional()")
                        return zod_base, validators
                else:
                    # Union without None
                    zod_types = [self.python_type_to_zod(arg, None)[0] for arg in args]
                    zod_base = f"z.union([{', '.join(zod_types)}])"

            # Handle List/Array
            elif origin in (list, tuple):
                args = get_args(py_type)
                if args:
                    item_zod, item_validators = self.python_type_to_zod(args[0], None)
                    if item_validators:
                        item_zod = item_zod + "".join(item_validators)
                    zod_base = f"z.array({item_zod})"
                else:
                    zod_base = "z.array(z.any())"

            # Handle Dict/Record
            elif origin is dict:
                args = get_args(py_type)
                if len(args) == 2:
                    val_zod, val_validators = self.python_type_to_zod(args[1], None)
                    if val_validators:
                        val_zod = val_zod + "".join(val_validators)
                    zod_base = f"z.record(z.string(), {val_zod})"
                else:
                    zod_base = "z.record(z.string(), z.any())"

            else:
                zod_base = "z.any()"

        # Add Pydantic field validators
        if field_info:
            # String validations
            if hasattr(field_info, "min_length") and field_info.min_length is not None:
                validators.append(f".min({field_info.min_length})")
            if hasattr(field_info, "max_length") and field_info.max_length is not None:
                validators.append(f".max({field_info.max_length})")
            if hasattr(field_info, "pattern") and field_info.pattern is not None:
                validators.append(f".regex(/{field_info.pattern}/)")

            # Number validations
            if hasattr(field_info, "ge") and field_info.ge is not None:
                validators.append(f".gte({field_info.ge})")
            if hasattr(field_info, "gt") and field_info.gt is not None:
                validators.append(f".gt({field_info.gt})")
            if hasattr(field_info, "le") and field_info.le is not None:
                validators.append(f".lte({field_info.le})")
            if hasattr(field_info, "lt") and field_info.lt is not None:
                validators.append(f".lt({field_info.lt})")

        return zod_base, validators

    def extract_enum(self, enum_class: type[Enum]) -> EnumDef:
        """Extract enum definition from Python Enum class."""
        values = {member.name: member.value for member in enum_class}
        return EnumDef(
            name=enum_class.__name__,
            values=values,
            docstring=inspect.getdoc(enum_class),
        )

    def extract_model(self, model_class: type[BaseModel]) -> ModelDef:
        """Extract model definition from Pydantic BaseModel."""
        fields = []

        # Get parent class required fields for inheritance handling
        parent_required_fields: set[str] = set()
        for base in model_class.__bases__:
            if base is not BaseModel and issubclass(base, BaseModel):
                for field_name, field_info in base.model_fields.items():
                    if field_info.is_required():
                        parent_required_fields.add(field_name)

        for field_name, field_info in model_class.model_fields.items():
            # Get field type
            field_type = field_info.annotation

            # Convert to TypeScript and Zod
            ts_type = self.python_type_to_typescript(field_type)
            zod_base, validators = self.python_type_to_zod(field_type, field_info)
            zod_type = zod_base + "".join(validators)

            # Check if required
            # If parent has field as required, child must also treat it as required
            # even if it has a default value (TypeScript inheritance requirement)
            required = field_info.is_required() or field_name in parent_required_fields

            # Get default value
            default = field_info.default if not required else None

            # Get description
            description = field_info.description

            fields.append(
                FieldDef(
                    name=field_name,
                    python_type=str(field_type),
                    typescript_type=ts_type,
                    zod_type=zod_type,
                    required=required,
                    default=default,
                    description=description,
                    validators=validators,
                )
            )

        # Determine base class
        base_class = None
        for base in model_class.__bases__:
            if base is not BaseModel and issubclass(base, BaseModel):
                base_class = base.__name__
                break

        return ModelDef(
            name=model_class.__name__,
            fields=fields,
            docstring=inspect.getdoc(model_class),
            base_class=base_class,
        )

    def generate_typescript(self) -> str:
        """Generate TypeScript interfaces from extracted definitions."""
        lines = [
            "/* eslint-disable @typescript-eslint/no-explicit-any */",
            "/**",
            " * AUTO-GENERATED FILE - DO NOT EDIT",
            " * ",
            " * Generated from Pydantic models by scripts/generate_types.py",
            " * To regenerate: python scripts/generate_types.py",
            " */",
            "",
        ]

        # Add frontend-only types that are referenced by generated code
        # These types are defined here because they're referenced by generated types
        # but are frontend-specific (not in backend Pydantic models)
        if self.referenced_frontend_types:
            lines.extend(
                [
                    "// ============================================================================",
                    "// Frontend-Only Types (referenced by generated code but not in backend)",
                    "// These types are frontend-specific and defined here to resolve references.",
                    "// ============================================================================",
                    "",
                ]
            )

            # Generate stub definitions for frontend-only types
            frontend_type_defs = {
                "ToolCall": """/**
 * Tool call information (frontend-only type).
 * Used for displaying tool execution details in the UI.
 */
export interface ToolCall {
  /** Unique tool call identifier */
  tool_call_id?: string;
  /** Tool name (e.g., "fetch_table_metadata") */
  tool_name: string;
  /** Human-readable tool name */
  friendly_name?: string;
  /** Tool execution status */
  status?: "completed" | "failed" | "running" | "pending";
  /** Tool arguments/parameters */
  arguments?: Record<string, unknown>;
  /** Tool execution result */
  result?: unknown;
  /** Error message if tool failed */
  error?: string;
  /** Execution duration in milliseconds */
  duration_ms?: number;
}
""",
            }

            for type_name in sorted(self.referenced_frontend_types):
                if type_name in frontend_type_defs:
                    lines.append(frontend_type_defs[type_name])

            lines.extend(
                [
                    "// ============================================================================",
                    "// End Frontend-Only Types",
                    "// ============================================================================",
                    "",
                ]
            )

        # Generate enums
        for enum_def in self.enums:
            if enum_def.docstring:
                lines.append("/**")
                for line in enum_def.docstring.split("\n"):
                    lines.append(f" * {line}")
                lines.append(" */")
            lines.append(f"export enum {enum_def.name} {{")
            for name, value in enum_def.values.items():
                lines.append(f'  {name} = "{value}",')
            lines.append("}")
            lines.append("")

        # Generate interfaces
        for model_def in self.models:
            if model_def.docstring:
                lines.append("/**")
                for line in model_def.docstring.split("\n"):
                    lines.append(f" * {line}")
                lines.append(" */")

            extends = f" extends {model_def.base_class}" if model_def.base_class else ""
            lines.append(f"export interface {model_def.name}{extends} {{")

            for field in model_def.fields:
                if field.description:
                    lines.append(f"  /** {field.description} */")
                optional = "?" if not field.required else ""
                lines.append(f"  {field.name}{optional}: {field.typescript_type};")

            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def generate_zod(self) -> str:
        """Generate Zod schemas from extracted definitions."""
        lines = [
            "/**",
            " * AUTO-GENERATED FILE - DO NOT EDIT",
            " * ",
            " * Generated from Pydantic models by scripts/generate_types.py",
            " * To regenerate: python scripts/generate_types.py",
            " */",
            "",
            'import { z } from "zod";',
            "",
        ]

        # Add import for frontend-only schemas if any are referenced
        if self.referenced_frontend_types:
            schema_imports = [
                f"{t}Schema" for t in sorted(self.referenced_frontend_types)
            ]
            lines.extend(
                [
                    "// Import frontend-only schemas (referenced by generated code but not in backend)",
                    "import {",
                ]
            )
            for schema_import in schema_imports:
                lines.append(f"  {schema_import},")
            lines.extend(
                [
                    '} from "./extended-schemas";',
                    "",
                ]
            )

        # Generate enum schemas
        for enum_def in self.enums:
            if enum_def.docstring:
                lines.append("/**")
                for line in enum_def.docstring.split("\n"):
                    lines.append(f" * {line}")
                lines.append(" */")
            enum_values = [f'"{v}"' for v in enum_def.values.values()]
            lines.append(
                f"export const {enum_def.name}Schema = z.enum([{', '.join(enum_values)}]);"
            )
            lines.append(
                f"export type {enum_def.name} = z.infer<typeof {enum_def.name}Schema>;"
            )
            lines.append("")

        # Generate model schemas
        for model_def in self.models:
            if model_def.docstring:
                lines.append("/**")
                for line in model_def.docstring.split("\n"):
                    lines.append(f" * {line}")
                lines.append(" */")

            if model_def.base_class:
                lines.append(
                    f"export const {model_def.name}Schema = {model_def.base_class}Schema.extend({{"
                )
            else:
                lines.append(f"export const {model_def.name}Schema = z.object({{")

            for field in model_def.fields:
                if field.description:
                    lines.append(f"  /** {field.description} */")
                lines.append(f"  {field.name}: {field.zod_type},")

            lines.append("});")
            lines.append(
                f"export type {model_def.name} = z.infer<typeof {model_def.name}Schema>;"
            )
            lines.append("")

        return "\n".join(lines)


def main():
    """Main entry point for type generation."""
    print("🔧 Generating TypeScript types and Zod schemas from Pydantic models...")

    # Import API models
    # Import LLM schema models (used by report types)
    from starboard_core.domain.models.llm_schemas import (
        Analysis,
        CodeLineRef,
        CurrentState,
        EffortEstimate,
        Finding,
        Fix,
        ImpactEstimate,
        NextStepAction,
        Proofs,
        QueryRewrite,
        ReferenceMaterial,
        Summary,
    )

    # Import report type models
    from starboard_core.domain.models.report_types import (
        AdvisorReport,
        AgentReport,
        AnalyticsFinding,
        AnalyticsReport,
        CostImpact,
        CostSummary,
        TopContributor,
        VisualizationRecommendation,
    )
    from starboard_server.api.models import (
        ChatEvent,
        ClarificationRequestEventData,
        ConversationConfig,
        ConversationResponse,
        # Request/Response models
        CreateConversationRequest,
        # Configuration models
        DomainModelConfig,
        # Enums
        EventType,
        FeedbackCategoryEnum,
        FeedbackRatingEnum,
        # Core models
        Message,
        MessageRole,
        MessageStatus,
        RespondToClarificationRequest,
        RespondToClarificationResponse,
        RespondToSolicitationRequest,
        RespondToSolicitationResponse,
        SendMessageRequest,
        SubmitFeedbackRequest,
    )

    generator = TypeGenerator()

    # Extract enums
    print("  📋 Extracting enums...")
    generator.enums.append(generator.extract_enum(EventType))
    generator.enums.append(generator.extract_enum(MessageRole))
    generator.enums.append(generator.extract_enum(MessageStatus))
    generator.enums.append(generator.extract_enum(FeedbackRatingEnum))
    generator.enums.append(generator.extract_enum(FeedbackCategoryEnum))

    # Extract API models
    print("  📦 Extracting API models...")
    # Configuration models first (referenced by others)
    generator.models.append(generator.extract_model(DomainModelConfig))
    generator.models.append(generator.extract_model(ConversationConfig))
    # Core models
    generator.models.append(generator.extract_model(Message))
    generator.models.append(generator.extract_model(ConversationResponse))
    generator.models.append(generator.extract_model(ChatEvent))
    # Request/Response models
    generator.models.append(generator.extract_model(CreateConversationRequest))
    generator.models.append(generator.extract_model(SendMessageRequest))
    generator.models.append(generator.extract_model(SubmitFeedbackRequest))
    generator.models.append(generator.extract_model(RespondToClarificationRequest))
    generator.models.append(generator.extract_model(RespondToClarificationResponse))
    generator.models.append(generator.extract_model(RespondToSolicitationRequest))
    generator.models.append(generator.extract_model(RespondToSolicitationResponse))
    # Event data models
    generator.models.append(generator.extract_model(ClarificationRequestEventData))

    # Extract LLM schema models (used by report types)
    print("  📦 Extracting LLM schema models...")
    # Supporting models first (referenced by others)
    generator.models.append(generator.extract_model(CodeLineRef))
    generator.models.append(generator.extract_model(ReferenceMaterial))
    generator.models.append(generator.extract_model(CurrentState))
    generator.models.append(generator.extract_model(Summary))
    generator.models.append(generator.extract_model(NextStepAction))
    generator.models.append(generator.extract_model(EffortEstimate))
    generator.models.append(generator.extract_model(ImpactEstimate))
    generator.models.append(generator.extract_model(Fix))
    generator.models.append(generator.extract_model(Proofs))
    generator.models.append(generator.extract_model(Finding))
    generator.models.append(generator.extract_model(QueryRewrite))
    generator.models.append(generator.extract_model(Analysis))

    # Extract report type models
    print("  📦 Extracting report type models...")
    # Supporting models first (referenced by report types)
    generator.models.append(generator.extract_model(TopContributor))
    generator.models.append(generator.extract_model(CostImpact))
    generator.models.append(generator.extract_model(CostSummary))
    generator.models.append(generator.extract_model(VisualizationRecommendation))
    generator.models.append(generator.extract_model(AnalyticsFinding))
    # Report types (base and specialized)
    generator.models.append(generator.extract_model(AgentReport))
    generator.models.append(generator.extract_model(AdvisorReport))
    generator.models.append(generator.extract_model(AnalyticsReport))

    # Note: Event-specific data schemas (for StreamingChatEvent.data) are NOT generated
    # because they are transformations (via to_sse_data() methods), not direct Pydantic models.
    # These remain in the manual event-schemas.ts file and are tested/validated in Phase 9.

    # Generate TypeScript
    print("  ✨ Generating TypeScript interfaces...")
    typescript_code = generator.generate_typescript()
    ts_output = project_root / "frontend" / "lib" / "types" / "generated-api.ts"
    ts_output.write_text(typescript_code)
    print(f"     ✅ {ts_output}")

    # Generate Zod schemas
    print("  ✨ Generating Zod schemas...")
    zod_code = generator.generate_zod()
    zod_output = (
        project_root / "frontend" / "lib" / "validation" / "generated-schemas.ts"
    )
    zod_output.write_text(zod_code)
    print(f"     ✅ {zod_output}")

    print("\n✅ Type generation complete!")
    print(
        f"   Generated {len(generator.enums)} enums and {len(generator.models)} models"
    )
    if generator.referenced_frontend_types:
        print(
            f"   Frontend-only types referenced: {', '.join(sorted(generator.referenced_frontend_types))}"
        )
        print("   (These are imported from extended-schemas.ts / defined inline)")
    print(f"   Output: {ts_output.relative_to(project_root)}")
    print(f"   Output: {zod_output.relative_to(project_root)}")


if __name__ == "__main__":
    main()
