#!/usr/bin/env python3
# Copyright (c) 2025 Databricks, Inc.
# Licensed under the Databricks Open Model License. See LICENSE for the full text.
"""port_to_opencode.py — Repeatable, idempotent converter from canonical Starboard
definitions to OpenCode format.

Sources read (all relative to repo root):
  skills : packages/starboard-skills/skills/starboard/<domain>/SKILL.md
  agents : packages/starboard-skills/agents/*.yaml  (canonical host-neutral defs)
  rules  : plugin/rules/*.md  (all except README.md)

Output written to:
  packages/starboard-distribution/opencode/
    skills/<name>/SKILL.md   — OpenCode skill files
    agents/<name>.md         — OpenCode agent files
    AGENTS.md                — Combined project-context rules

OpenCode format references:
  https://opencode.ai/docs/agents/
  https://opencode.ai/docs/skills/
  https://opencode.ai/docs/rules/
  https://opencode.ai/docs/models/

Schema-mapping table
────────────────────
Skill  (SKILL.md → opencode/skills/<name>/SKILL.md):
  name          → name           (required; must match directory name)
  description   → description    (required; 1–1024 chars)
  allowed-tools → (stripped)     (Claude Code–specific; not a valid OC skill key)
  (added)       compatibility: opencode
  (added)       metadata.source: canonical path
  body          → body unchanged

Agent  (agents/*.yaml → opencode/agents/<name>.md):
  name                → filename stem
  description         → description
  kind=orchestrator   → mode: primary
  kind=subagent       → mode: subagent
  kind=autonomous     → mode: subagent  (OC has no native autonomous mode; noted in body)
  model=sonnet        → anthropic/claude-sonnet-4-20250514
  model=haiku         → anthropic/claude-haiku-3-20240307
  model=opus          → anthropic/claude-opus-4-20250514
  tools: Bash         → permission.bash: allow
  tools: Read         → permission.read: allow
  tools: Write/Edit   → permission.edit: allow
  tools: Task         → permission.task: allow
  tools: Glob         → permission.list: allow
  tools: Grep         → permission.grep: allow
  body                → system prompt body

Rules  (plugin/rules/*.md → opencode/AGENTS.md):
  Per-domain .md files concatenated; frontmatter stripped.
  starboard.md index body used as preamble.

Usage:
  python scripts/port_to_opencode.py
  python scripts/port_to_opencode.py --check          # drift check (CI)
  python scripts/port_to_opencode.py --out-dir DIR    # custom output directory
  python scripts/port_to_opencode.py --repo-root DIR  # custom repo root

make port-opencode snippet (add to Makefile):
  port-opencode:
      python scripts/port_to_opencode.py
  .PHONY: port-opencode

  test-opencode:
      python scripts/port_to_opencode.py --check
  .PHONY: test-opencode
"""

from __future__ import annotations

import argparse
import difflib
import filecmp
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Map short model hints used in canonical YAML to the OpenCode provider/model-id format.
#: Format: anthropic/<model-id>  (see https://opencode.ai/docs/models/)
MODEL_MAP: dict[str, str] = {
    "sonnet": "anthropic/claude-sonnet-4-20250514",
    "haiku": "anthropic/claude-haiku-3-20240307",
    "opus": "anthropic/claude-opus-4-20250514",
}

#: Canonical tool name → OpenCode permission key.
#: OpenCode permission keys: read/edit/list/bash/grep/task/lsp/webfetch/websearch
TOOL_PERM_MAP: dict[str, str] = {
    "Bash": "bash",
    "Read": "read",
    "Write": "edit",
    "Edit": "edit",
    "Task": "task",
    "Glob": "list",
    "Grep": "grep",
    "LSP": "lsp",
    "WebFetch": "webfetch",
    "WebSearch": "websearch",
}

_GENERATED_COMMENT = (
    "<!-- Generated by scripts/port_to_opencode.py — do not edit directly.\n"
    "     Regenerate: python scripts/port_to_opencode.py -->\n\n"
)


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def _repo_root() -> Path:
    """Walk upward from this script until we find the monorepo root."""
    for parent in Path(__file__).resolve().parents:
        if (parent / "packages" / "starboard-skills" / "skills").is_dir():
            return parent
    raise RuntimeError(
        "Could not locate repo root containing packages/starboard-skills/skills. "
        "Pass --repo-root explicitly."
    )


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------

def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Split YAML frontmatter from a markdown body.

    Returns (frontmatter_dict, body_text).  Returns ({}, text) when there is
    no leading ``---`` block.
    """
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    fm: dict[str, Any] = yaml.safe_load(text[3:end]) or {}
    body = text[end + 4:].lstrip("\n")
    return fm, body


def _render_frontmatter(data: dict[str, Any]) -> str:
    """Render *data* as a YAML frontmatter block (``--- ... ---\\n``)."""
    dumped = yaml.dump(
        data,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        width=4096,  # large width → no mid-string line wrapping
    )
    return f"---\n{dumped}---\n"


# ---------------------------------------------------------------------------
# Mapping helpers
# ---------------------------------------------------------------------------

def _map_model(hint: str | None) -> str:
    """Return the OpenCode provider/model-id for a short model hint."""
    if not hint:
        return MODEL_MAP["sonnet"]
    return MODEL_MAP.get(hint.strip().lower(), f"anthropic/{hint.strip()}")


def _tools_to_permissions(tools: list[str]) -> dict[str, str]:
    """Convert a canonical tools list to an OpenCode permission map."""
    perms: dict[str, str] = {}
    for t in tools:
        key = TOOL_PERM_MAP.get(t)
        if key and key not in perms:
            perms[key] = "allow"
    return perms


def _kind_to_mode(kind: str | None) -> str:
    """Map canonical agent kind to an OpenCode mode value.

    OpenCode supports: primary | subagent | all
    Autonomous agents have no native OC mode; they become subagents with a
    scheduling note injected into the body.
    """
    if kind == "orchestrator":
        return "primary"
    return "subagent"  # subagent and autonomous both map here


# ---------------------------------------------------------------------------
# Converters
# ---------------------------------------------------------------------------

def convert_skill(skill_path: Path) -> tuple[str, str]:
    """Convert a canonical SKILL.md to OpenCode format.

    Returns (skill_name, file_content).

    OpenCode skill spec (https://opencode.ai/docs/skills/):
    - Frontmatter keys: name (required), description (required),
      compatibility (optional), metadata (optional str→str map).
    - Unknown keys are ignored; ``allowed-tools`` is stripped (Claude Code–only).
    """
    text = skill_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(text)

    name: str = fm.get("name") or skill_path.parent.name
    description: str = (fm.get("description") or "").strip()

    oc_fm: dict[str, Any] = {
        "name": name,
        "description": description,
        "compatibility": "opencode",
        "metadata": {
            "source": f"packages/starboard-skills/skills/starboard/{name}/SKILL.md",
        },
    }

    content = _render_frontmatter(oc_fm) + "\n" + body
    return name, content


def convert_agent(agent_path: Path) -> tuple[str, str]:
    """Convert a canonical agent YAML to an OpenCode agent .md file.

    Returns (agent_name, file_content).

    OpenCode agent spec (https://opencode.ai/docs/agents/):
    - Frontmatter keys: description (required), mode (primary/subagent/all),
      model (provider/model-id), permission (map of tool→action), steps, etc.
    - Body becomes the agent's system prompt.
    """
    raw = agent_path.read_text(encoding="utf-8")
    data: dict[str, Any] = yaml.safe_load(raw) or {}

    name: str = data.get("name") or agent_path.stem
    description: str = (data.get("description") or "").strip()
    kind: str | None = data.get("kind")
    tools: list[str] = data.get("tools") or []
    body: str = (data.get("body") or "").rstrip("\n")

    mode = _kind_to_mode(kind)
    model = _map_model(data.get("model"))
    perms = _tools_to_permissions(tools)

    oc_fm: dict[str, Any] = {"description": description, "mode": mode, "model": model}
    if perms:
        oc_fm["permission"] = perms

    # Autonomous agents: prepend scheduling note (OC has no native scheduled mode)
    if kind == "autonomous":
        trigger = (data.get("trigger_recipe") or "").strip()
        note_lines = [
            "> **OpenCode scheduling note:** OpenCode has no native autonomous/",
            "> scheduled mode. Wire the trigger externally (cron, CI, or a hook).",
        ]
        if trigger:
            note_lines.append(">")
            for line in trigger.splitlines():
                note_lines.append(f"> {line}")
        body = "\n".join(note_lines) + "\n\n" + body

    content = _render_frontmatter(oc_fm) + "\n" + body + "\n"
    return name, content


def convert_rules(rule_paths: list[Path], index_path: Path | None = None) -> str:
    """Combine per-domain rule files into a single OpenCode AGENTS.md.

    The index file (starboard.md) provides the preamble; per-domain files are
    appended in alphabetical order with frontmatter stripped.
    """
    parts: list[str] = [
        "# Starboard — OpenCode Project Rules\n\n",
        _GENERATED_COMMENT,
    ]

    if index_path and index_path.exists():
        text = index_path.read_text(encoding="utf-8")
        _, body = parse_frontmatter(text)
        parts.append(body.rstrip("\n") + "\n\n---\n\n")

    for rp in sorted(rule_paths, key=lambda p: p.stem):
        text = rp.read_text(encoding="utf-8")
        fm, body = parse_frontmatter(text)
        title: str = fm.get("title") or rp.stem
        parts.append(f"## {title}\n\n")
        parts.append(body.rstrip("\n") + "\n\n")

    return "".join(parts)


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

def build(repo_root: Path, out_dir: Path) -> None:
    """Generate the full OpenCode bundle into *out_dir* (idempotent)."""
    skills_root = repo_root / "packages" / "starboard-skills" / "skills" / "starboard"
    agents_root = repo_root / "packages" / "starboard-skills" / "agents"
    rules_root = repo_root / "plugin" / "rules"

    # ── Skills ──────────────────────────────────────────────────────────────
    skills_out = out_dir / "skills"
    skills_out.mkdir(parents=True, exist_ok=True)

    skill_paths = sorted(skills_root.glob("*/SKILL.md"))
    if not skill_paths:
        raise FileNotFoundError(
            f"No SKILL.md files found under {skills_root}. "
            "Verify --repo-root points at the correct location."
        )
    for sp in skill_paths:
        skill_name, content = convert_skill(sp)
        dest_dir = skills_out / skill_name
        dest_dir.mkdir(exist_ok=True)
        (dest_dir / "SKILL.md").write_text(content, encoding="utf-8")
    print(f"  skills  : {len(skill_paths)} files  →  {skills_out}")

    # ── Agents ──────────────────────────────────────────────────────────────
    agents_out = out_dir / "agents"
    agents_out.mkdir(parents=True, exist_ok=True)

    agent_paths = sorted(agents_root.glob("*.yaml"))
    if not agent_paths:
        raise FileNotFoundError(
            f"No *.yaml agent files found under {agents_root}. "
            "Verify --repo-root points at the correct location."
        )
    for ap in agent_paths:
        agent_name, content = convert_agent(ap)
        (agents_out / f"{agent_name}.md").write_text(content, encoding="utf-8")
    print(f"  agents  : {len(agent_paths)} files  →  {agents_out}")

    # ── Rules / AGENTS.md ───────────────────────────────────────────────────
    index_path = rules_root / "starboard.md"
    rule_paths = [
        p for p in rules_root.glob("*.md")
        if p.name not in ("README.md", "starboard.md")
    ]
    rules_content = convert_rules(rule_paths, index_path)
    agents_md = out_dir / "AGENTS.md"
    agents_md.write_text(rules_content, encoding="utf-8")
    print(f"  rules   : {len(rule_paths)} domain files  →  {agents_md}")


# ---------------------------------------------------------------------------
# Drift check
# ---------------------------------------------------------------------------

def check(repo_root: Path, committed_dir: Path) -> bool:
    """Regenerate into a temp dir and diff against *committed_dir*.

    Returns True (clean / no drift) or False (drift detected).
    """
    with tempfile.TemporaryDirectory(prefix="oc-port-check-") as tmp_str:
        tmp = Path(tmp_str)
        build(repo_root, tmp)

        diffs: list[str] = []

        # Files present in generated output
        for gen_file in sorted(tmp.rglob("*")):
            if not gen_file.is_file():
                continue
            rel = gen_file.relative_to(tmp)
            committed_file = committed_dir / rel
            if not committed_file.exists():
                diffs.append(f"  NEW (not committed): {rel}\n")
                continue
            if not filecmp.cmp(str(gen_file), str(committed_file), shallow=False):
                gen_lines = gen_file.read_text(encoding="utf-8").splitlines(keepends=True)
                com_lines = committed_file.read_text(encoding="utf-8").splitlines(keepends=True)
                diff_lines = list(
                    difflib.unified_diff(
                        com_lines,
                        gen_lines,
                        fromfile=f"committed/{rel}",
                        tofile=f"generated/{rel}",
                        n=3,
                    )
                )
                if diff_lines:
                    diffs.extend(diff_lines)

        # Files committed but no longer generated
        for com_file in sorted(committed_dir.rglob("*")):
            if not com_file.is_file():
                continue
            rel = com_file.relative_to(committed_dir)
            if not (tmp / rel).exists():
                diffs.append(f"  REMOVED (not in generated output): {rel}\n")

    if diffs:
        print("Drift detected in packages/starboard-distribution/opencode/:")
        print("".join(diffs))
        print("\nRegenerate: python scripts/port_to_opencode.py")
        return False

    print("No drift detected — bundle is up to date.")
    return True


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert canonical Starboard definitions to OpenCode format.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        metavar="DIR",
        help="Monorepo root (auto-detected from script location if omitted).",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        metavar="DIR",
        help=(
            "Output directory (default: packages/starboard-distribution/opencode/ "
            "under the repo root)."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Regenerate to a temp dir and diff against the committed bundle. "
            "Exits 1 if any file differs (CI drift check)."
        ),
    )
    args = parser.parse_args(argv)

    repo = args.repo_root or _repo_root()
    out_dir = args.out_dir or (repo / "packages" / "starboard-distribution" / "opencode")

    if args.check:
        print("Checking OpenCode bundle for drift…")
        return 0 if check(repo, out_dir) else 1

    print(f"Generating OpenCode bundle → {out_dir}")
    build(repo, out_dir)
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
