/**
 * Contract Tests: Frontend Event Validation
 *
 * Validates backend-generated event fixtures against frontend Zod schemas.
 * These tests ensure that the actual SSE events from the backend match
 * the frontend's expectations.
 *
 * IMPORTANT: These tests validate JSON fixtures generated by backend tests.
 * If tests fail, it means backend event structure has changed and frontend
 * schemas need to be updated to match.
 */

import { describe, it, expect } from '@jest/globals';
import { readFileSync } from 'fs';
import { join } from 'path';
import {
  validateStreamingEvent,
  formatValidationError,
} from '../event-schemas';

// Path to backend-generated fixtures
const FIXTURES_DIR = join(__dirname, '../../../../tests/contract/backend/fixtures');

function loadFixture(filename: string): unknown {
  const filepath = join(FIXTURES_DIR, filename);
  const content = readFileSync(filepath, 'utf-8');
  return JSON.parse(content);
}

function createEvent(eventType: string, data: unknown): Record<string, unknown> {
  return {
    type: eventType,  // Frontend schema uses 'type' not 'event_type'
    data,
    event_id: `evt_test_${Date.now()}`,
    timestamp: new Date().toISOString(),
  };
}

describe('Contract Tests: Backend Event Validation', () => {
  describe('final_output event', () => {
    it('should validate all status variations', () => {
      const fixtures = loadFixture('final_output.json') as Record<string, unknown>;
      const statuses = ['success', 'error', 'budget_exceeded', 'max_steps_reached', 'unknown'];

      statuses.forEach((status) => {
        const data = fixtures[status];
        const event = createEvent('final_output', data);

        const result = validateStreamingEvent(event);

        if (!result.success) {
          console.error(`❌ Validation failed for status: ${status}`);
          console.error(formatValidationError(result.error));
          console.error('Fixture data:', JSON.stringify(data, null, 2));
        }

        expect(result.success).toBe(true);
      });
    });

    it('should handle null report fields', () => {
      const data = loadFixture('final_output_null_reports.json');
      const event = createEvent('final_output', data);

      const result = validateStreamingEvent(event);

      if (!result.success) {
        console.error('❌ Validation failed for null reports');
        console.error(formatValidationError(result.error));
      }

      expect(result.success).toBe(true);
    });
  });

  describe('thinking event (message.delta)', () => {
    it('should validate thinking event', () => {
      const fixture = loadFixture('thinking_message_delta.json') as { event_type: string; data: unknown };
      const event = {
        type: fixture.event_type,  // Convert event_type to type
        data: fixture.data,
        event_id: 'evt_test_thinking',
        timestamp: new Date().toISOString(),
      };

      const result = validateStreamingEvent(event);

      if (!result.success) {
        console.error('❌ Validation failed for thinking event');
        console.error(formatValidationError(result.error));
      }

      expect(result.success).toBe(true);
      expect(event.type).toBe('message.delta');
    });
  });

  describe('tool events', () => {
    it('should validate tool.call.start event', () => {
      const data = loadFixture('tool_call_start.json');
      const event = createEvent('tool.call.start', data);

      const result = validateStreamingEvent(event);

      if (!result.success) {
        console.error('❌ Validation failed for tool.call.start');
        console.error(formatValidationError(result.error));
      }

      expect(result.success).toBe(true);
    });

    it('should validate successful tool.call.result event', () => {
      const data = loadFixture('tool_call_result_success.json');
      const event = createEvent('tool.call.result', data);

      const result = validateStreamingEvent(event);

      if (!result.success) {
        console.error('❌ Validation failed for tool.call.result (success)');
        console.error(formatValidationError(result.error));
      }

      expect(result.success).toBe(true);
    });

    it('should validate failed tool.call.result event', () => {
      const data = loadFixture('tool_call_result_failure.json');
      const event = createEvent('tool.call.result', data);

      const result = validateStreamingEvent(event);

      if (!result.success) {
        console.error('❌ Validation failed for tool.call.result (failure)');
        console.error(formatValidationError(result.error));
      }

      expect(result.success).toBe(true);
    });
  });

  describe('step.complete event', () => {
    it('should validate step.complete event', () => {
      const data = {
        reasoning: "Analyzed query plan and identified bottleneck",
        tools_called: ["analyze_query_plan", "fetch_table_metadata"],
        message_id: "msg_test123",
      };
      const event = createEvent('step.complete', data);

      const result = validateStreamingEvent(event);

      if (!result.success) {
        console.error('❌ Validation failed for step.complete');
        console.error(formatValidationError(result.error));
      }

      expect(result.success).toBe(true);
    });
  });

  describe('error event', () => {
    it('should validate error event', () => {
      const data = {
        message_id: "msg_test123",
        error: {
          message: "Failed to execute query",
          code: "QUERY_ERROR",
          details: { sql_error: "Table not found" }
        }
      };
      const event = createEvent('error', data);

      const result = validateStreamingEvent(event);

      if (!result.success) {
        console.error('❌ Validation failed for error event');
        console.error(formatValidationError(result.error));
      }

      expect(result.success).toBe(true);
      expect(event.type).toBe('error');
    });
  });

  describe('next_steps event', () => {
    it('should validate next_steps event', () => {
      const data = {
        message_id: "msg_test123",
        next_steps: [
          {
            id: "opt1",
            number: 1,
            title: "Optimize query",
            description: "Rewrite query for better performance",
            action_type: "tool_call",
            target_agent: null,
            tool_name: "optimize_query",
            parameters: { query_id: "123" }
          },
          {
            id: "opt2",
            number: 2,
            title: "Analyze query plan",
            description: null,
            action_type: "continue",
            target_agent: null,
            tool_name: null,
            parameters: null
          }
        ]
      };
      const event = createEvent('next_steps', data);

      const result = validateStreamingEvent(event);

      if (!result.success) {
        console.error('❌ Validation failed for next_steps');
        console.error(formatValidationError(result.error));
      }

      expect(result.success).toBe(true);
    });
  });

  describe('clarification_request event', () => {
    it('should validate clarification_request event', () => {
      const data = {
        message_id: "msg_test123",
        conversation_id: "conv_test456",
        clarification_id: "clar_abc123",
        clarification_type: "missing_parameter",
        question: "What warehouse size would you like?",
        options: [
          { option_id: "1", display_text: "Small", value: "small" },
          { option_id: "2", display_text: "Medium", value: "medium" }
        ],
        allow_custom_response: true,
        is_required: true,
        target_tool: "create_warehouse"
      };
      const event = createEvent('clarification.request', data);

      const result = validateStreamingEvent(event);

      if (!result.success) {
        console.error('❌ Validation failed for clarification_request');
        console.error(formatValidationError(result.error));
      }

      expect(result.success).toBe(true);
    });
  });

  describe('Regression Tests', () => {
    it('should NOT allow status values that are not in the schema', () => {
      // This test ensures we catch when backend adds new status values
      const data = {
        message_id: 'msg_test',
        output: {
          status: 'new_unexpected_status', // This should fail validation
          formatted_report: null,
          complete_report: null,
          tokens_used: 0,
          cost_usd: 0.0,
        },
      };

      const event = createEvent('final_output', data);
      const result = validateStreamingEvent(event);

      // This SHOULD fail - we want to catch unexpected values
      expect(result.success).toBe(false);

      if (result.success === false) {
        const errorMessage = formatValidationError(result.error);
        // Zod v4 uses "Invalid option" instead of "Invalid enum value"
        expect(errorMessage).toContain('Invalid option');
      }
    });

    it('should handle missing required fields gracefully', () => {
      // Test that we properly detect missing required fields
      const data = {
        // missing message_id
        output: {
          status: 'success',
        },
      };

      const event = createEvent('final_output', data);
      const result = validateStreamingEvent(event);

      // This SHOULD fail - message_id is required
      expect(result.success).toBe(false);

      if (result.success === false) {
        const errorMessage = formatValidationError(result.error);
        expect(errorMessage).toContain('message_id');
      }
    });
  });

  describe('Edge Cases', () => {
    it('should handle tool calls with empty arguments', () => {
      const data = {
        message_id: 'msg_test',
        tool_call: {
          tool_call_id: 'call_123',
          tool_name: 'test_tool',
          friendly_name: 'Test Tool',
          status: 'running',
          arguments: {}, // Empty arguments object
        },
      };

      const event = createEvent('tool.call.start', data);
      const result = validateStreamingEvent(event);

      expect(result.success).toBe(true);
    });

    it('should handle tool results with null error', () => {
      const data = {
        message_id: 'msg_test',
        tool_call: {
          tool_call_id: 'call_123',
          tool_name: 'test_tool',
          friendly_name: 'Test Tool',
          status: 'completed',
          success: true,
          error: null, // Explicitly null
          result: 'Success result',
        },
      };

      const event = createEvent('tool.call.result', data);
      const result = validateStreamingEvent(event);

      expect(result.success).toBe(true);
    });
  });
});

