# Copyright (c) 2025 Databricks, Inc.
# Licensed under the Databricks Open Model License. See LICENSE for the full text.
"""Unit tests for the agent-experience catalog generator (Task E2, D-3.1).

Validates:
- ``gen_catalog.py --check`` passes on the committed output (regenerate-and-diff,
  mirroring ``test_gen_rulesets.py``).
- Every catalogued surface resolves to a real thing: skills → skill dir,
  agents → canonical YAML, tools → ``ALL_TOOL_METADATA`` key, helpers →
  importable module, CLI commands → importable dispatch symbol.
- The tool count equals ``len(ALL_TOOL_METADATA)`` (D-3.2), with no dead
  references in the committed MCP-tools page.
- Governance: no internal namespaces on any generated page or the guide.
- Every generated page is wired into the mkdocs nav.
"""

from __future__ import annotations

import importlib
import importlib.util
import re
import subprocess
import sys
from pathlib import Path
from types import ModuleType

import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# packages/starboard/tests/unit/catalog/test_gen_catalog.py → repo root [5]
_REPO_ROOT = Path(__file__).resolve().parents[5]
_SCRIPTS_DIR = _REPO_ROOT / "scripts"
_GENERATOR = _SCRIPTS_DIR / "gen_catalog.py"
_REFERENCE_DIR = _REPO_ROOT / "docs" / "reference"
_SKILLS_DIR = _REPO_ROOT / "packages" / "starboard-skills" / "skills" / "starboard"
_AGENTS_DIR = _REPO_ROOT / "packages" / "starboard-skills" / "agents"
_MKDOCS = _REPO_ROOT / "mkdocs.yml"

_EXPECTED_PAGES = [
    _REFERENCE_DIR / "CATALOG.md",
    _REFERENCE_DIR / "skills" / "INDEX.md",
    _REFERENCE_DIR / "mcp-tools" / "INDEX.md",
    _REFERENCE_DIR / "agents" / "INDEX.md",
    _REFERENCE_DIR / "cli-commands" / "INDEX.md",
    _REFERENCE_DIR / "progressive-helpers" / "INDEX.md",
    _REFERENCE_DIR / "plugins" / "INDEX.md",
]

_INTERNAL_NAMESPACES = [
    "centralized_system_tables",
    "fin_live_gold",
    "gtm_",
    "eng_",
    "logfood",
    "ClickHouse",
    "hmr_stack_hash",
]


# ---------------------------------------------------------------------------
# Load gen_catalog.py from scripts/ (not an installed package)
# ---------------------------------------------------------------------------


def _load_gen_catalog() -> ModuleType:
    spec = importlib.util.spec_from_file_location("gen_catalog", _GENERATOR)
    assert spec is not None and spec.loader is not None, (
        f"Could not load gen_catalog.py from {_GENERATOR}"
    )
    mod = importlib.util.module_from_spec(spec)
    # Register before exec so dataclasses can resolve the module namespace
    # (dataclass field processing looks the module up in sys.modules).
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    return mod


gen_catalog = _load_gen_catalog()


def _first_backtick_token(line: str) -> str | None:
    m = re.match(r"^\|\s*`([^`]+)`", line)
    return m.group(1) if m else None


# ---------------------------------------------------------------------------
# Idempotency / drift
# ---------------------------------------------------------------------------


def test_generator_check_passes() -> None:
    """`gen_catalog.py --check` must report no stale committed pages."""
    result = subprocess.run(
        [sys.executable, str(_GENERATOR), "--check"],
        capture_output=True,
        text=True,
        cwd=str(_REPO_ROOT),
    )
    assert result.returncode == 0, (
        "gen_catalog.py --check reported stale files.\n"
        "Run `python scripts/gen_catalog.py` to regenerate, then commit.\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


@pytest.mark.parametrize("page", _EXPECTED_PAGES, ids=lambda p: str(p.name))
def test_page_exists_with_marker(page: Path) -> None:
    """Every catalog page exists and carries the GENERATED marker."""
    assert page.exists(), f"Missing catalog page: {page.relative_to(_REPO_ROOT)}"
    assert "GENERATED by scripts/gen_catalog.py" in page.read_text(encoding="utf-8"), (
        f"{page.name}: missing GENERATED marker"
    )


# ---------------------------------------------------------------------------
# Tool count + no dead references
# ---------------------------------------------------------------------------


def _registry_tool_names() -> set[str]:
    registry = importlib.import_module("starboard.agents.tools.registry")
    return set(registry.ALL_TOOL_METADATA.keys())


def test_tool_count_matches_registry() -> None:
    """The catalog's tool count must equal len(ALL_TOOL_METADATA) (D-3.2)."""
    n = len(_registry_tool_names())
    tools_page = (_REFERENCE_DIR / "mcp-tools" / "INDEX.md").read_text(encoding="utf-8")
    catalog = (_REFERENCE_DIR / "CATALOG.md").read_text(encoding="utf-8")
    assert f"**{n} tools**" in tools_page, f"mcp-tools page does not state {n} tools"
    assert f"**{n}**" in catalog, f"CATALOG.md does not state the {n} tool count"


def test_tool_rows_have_no_dead_references() -> None:
    """Every tool named in the committed MCP-tools table exists in the registry,
    and every registry tool is catalogued (100% coverage)."""
    registry_names = _registry_tool_names()
    tools_page = (_REFERENCE_DIR / "mcp-tools" / "INDEX.md").read_text(encoding="utf-8")
    # Tool rows are the ones whose first cell token is a registry tool candidate;
    # collect all first-backtick tokens that appear as table rows.
    listed: set[str] = set()
    for line in tools_page.splitlines():
        tok = _first_backtick_token(line)
        if tok and tok in registry_names:
            listed.add(tok)
    # No dead references: every catalogued tool token that looks like a tool row
    # must be a real registry key. Assert full coverage in both directions.
    assert listed == registry_names, (
        "MCP-tools catalog drifted from the registry.\n"
        f"Missing from catalog: {sorted(registry_names - listed)}\n"
        f"Extra in catalog: {sorted(listed - registry_names)}"
    )


def test_collected_tools_match_registry() -> None:
    """The generator's collector reads exactly the live registry keys."""
    collected = {e.name for e in gen_catalog.collect_tools()}
    assert collected == _registry_tool_names()


# ---------------------------------------------------------------------------
# Surface resolution (no entry names a non-existent surface)
# ---------------------------------------------------------------------------


def test_every_skill_resolves() -> None:
    for entry in gen_catalog.collect_skills():
        skill_dir = _SKILLS_DIR / entry.directory
        assert (skill_dir / "SKILL.md").is_file(), (
            f"Skill {entry.name!r} → {skill_dir} has no SKILL.md"
        )


def test_every_agent_resolves() -> None:
    for entry in gen_catalog.collect_agents():
        yaml_path = _AGENTS_DIR / f"{entry.name}.yaml"
        assert yaml_path.is_file(), f"Agent {entry.name!r} → {yaml_path} missing"


def test_every_implemented_helper_imports() -> None:
    for entry in gen_catalog.collect_helpers():
        if entry.implemented:
            # e.g. starboard_x.review — must be importable in this env.
            importlib.import_module(entry.module)


def test_every_cli_dispatch_symbol_imports() -> None:
    for entry in gen_catalog.collect_cli_commands():
        module_name, _, symbol = entry.dispatch.partition(":")
        module = importlib.import_module(module_name)
        assert hasattr(module, symbol), (
            f"CLI command {entry.command!r}: dispatch {entry.dispatch} not importable"
        )


def test_plugin_entry_point_group_is_public_contract() -> None:
    plugin = gen_catalog.collect_plugins()
    assert plugin.entry_point_group == "starboard.mcp_tools"
    page = (_REFERENCE_DIR / "plugins" / "INDEX.md").read_text(encoding="utf-8")
    assert "starboard.mcp_tools" in page


# ---------------------------------------------------------------------------
# Governance
# ---------------------------------------------------------------------------

_GOVERNED_FILES = _EXPECTED_PAGES + [_REPO_ROOT / "docs" / "guides" / "AGENT_EXPERIENCE.md"]


@pytest.mark.parametrize("path", _GOVERNED_FILES, ids=lambda p: str(p.name))
def test_no_internal_namespaces(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    for ns in _INTERNAL_NAMESPACES:
        assert ns not in text, f"{path.name}: contains internal namespace {ns!r}"


# ---------------------------------------------------------------------------
# mkdocs nav wiring (strict build requires every page in nav)
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("page", _EXPECTED_PAGES + [_REPO_ROOT / "docs" / "guides" / "AGENT_EXPERIENCE.md"],
                         ids=lambda p: str(p.name))
def test_page_wired_into_nav(page: Path) -> None:
    nav_ref = str(page.relative_to(_REPO_ROOT / "docs"))
    mkdocs = _MKDOCS.read_text(encoding="utf-8")
    assert nav_ref in mkdocs, f"{nav_ref} is not referenced in mkdocs.yml nav"
