# Copyright (c) 2025 Databricks, Inc.
# Licensed under the Databricks Open Model License. See LICENSE for the full text.
"""
ParsedLogParser - Builds SparkApplication from pre-parsed JSON data.

This parser rehydrates a SparkApplication from a previously parsed and saved
JSON representation. It handles both legacy Pandas-based data and new Polars format.
"""

from typing import Any

import polars as pl

from starboard_log_parser.domain.models.application import (
    SparkApplication,
)
from starboard_log_parser.domain.models.info import SparkApplicationInfo
from starboard_log_parser.domain.models.metadata import (
    SparkApplicationMetadata,
)


class ParsedLogParser:
    """
    Parses pre-computed/parsed Spark application data into domain models.

    This parser is used to rehydrate SparkApplication instances from JSON files
    that were previously generated by parsing raw Spark event logs. It's the
    simplest parser since all the heavy lifting (event parsing, aggregation) has
    already been done.

    Use cases:
        - Loading saved parse results for analysis
        - Testing with fixture data
        - API responses with pre-computed data

    Examples:
        >>> parser = ParsedLogParser()
        >>> data = {
        ...     "metadata": {...},
        ...     "jobData": {...},
        ...     "stageData": {...},
        ...     # ... other data
        ... }
        >>> app = parser.parse(data)
        >>> app.has_sql_data()
        True
    """

    @staticmethod
    def _ensure_string_keys(
        data: dict[Any, Any] | list[dict[Any, Any]],
    ) -> dict[str, Any] | list[dict[str, Any]]:
        """
        Ensure all dictionary keys are strings for Polars DataFrame creation.

        Polars requires string column names, but legacy data might have integer
        or other types as keys. This method converts all keys to strings.

        Args:
            data: Either column-oriented dict {'col': [vals]} or
                  row-oriented list [{'col': val}, ...]

        Returns:
            Data with all keys converted to strings

        Examples:
            >>> ParsedLogParser._ensure_string_keys({0: [1, 2], 1: [3, 4]})
            {'0': [1, 2], '1': [3, 4]}
            >>> ParsedLogParser._ensure_string_keys([{0: 1, 1: 2}])
            [{'0': 1, '1': 2}]
        """
        if isinstance(data, dict):
            # Column-oriented format: {'col': [values]}
            return {str(k): v for k, v in data.items()}
        elif isinstance(data, list) and data and isinstance(data[0], dict):
            # Row-oriented format: [{'col': val}, ...]
            return [{str(k): v for k, v in record.items()} for record in data]
        return data  # type: ignore[return-value]

    def _parse_metadata(self, raw_data: dict[str, Any]) -> SparkApplicationMetadata:
        """
        Parse metadata from raw JSON data.

        Args:
            raw_data: Full parsed application JSON

        Returns:
            Immutable SparkApplicationMetadata

        Raises:
            KeyError: If required metadata fields are missing
            ValueError: If metadata is malformed
        """
        metadata_dict = raw_data.get("metadata", {})

        # Parse application info
        app_info_dict = metadata_dict.get("application_info", {})
        app_info = SparkApplicationInfo(
            timestamp_start_ms=app_info_dict["timestamp_start_ms"],
            timestamp_end_ms=app_info_dict["timestamp_end_ms"],
            runtime_sec=app_info_dict["runtime_sec"],
            name=app_info_dict["name"],
            id=app_info_dict["id"],
            spark_version=app_info_dict["spark_version"],
            emr_version_tag=app_info_dict.get("emr_version_tag", ""),
            cloud_platform=app_info_dict.get("cloud_platform", ""),
            cloud_provider=app_info_dict.get("cloud_provider", ""),
            cluster_id=app_info_dict.get("cluster_id", ""),
        )

        # Parse metadata
        metadata = SparkApplicationMetadata(
            application_info=app_info,
            spark_params=metadata_dict.get("spark_params", {}),
            exists_sql=metadata_dict.get("existsSQL", False),
            exists_executors=metadata_dict.get("existsExecutors", False),
        )

        return metadata

    def _parse_dataframe(self, raw_data: dict[str, Any], key: str) -> pl.DataFrame:
        """
        Parse a DataFrame from raw JSON data.

        Args:
            raw_data: Full parsed application JSON
            key: Key to look up in raw_data (e.g., "jobData", "stageData")

        Returns:
            Polars DataFrame with string column names

        Raises:
            KeyError: If key is not found in raw_data
        """
        data = raw_data[key]
        data = self._ensure_string_keys(data)
        return pl.DataFrame(data)

    def parse(self, raw_data: dict[str, Any]) -> SparkApplication:
        """
        Parse pre-computed Spark application data into a domain model.

        Args:
            raw_data: Dictionary containing all parsed application data.
                      Expected keys: "metadata", "jobData", "stageData",
                      "taskData", "accumData", and optionally "sqlData",
                      "executors"

        Returns:
            Immutable SparkApplication domain model

        Raises:
            KeyError: If required keys are missing
            ValueError: If data is malformed or inconsistent

        Examples:
            >>> parser = ParsedLogParser()
            >>> data = load_json("my_spark_app.json")
            >>> app = parser.parse(data)
            >>> len(app.job_data)
            42
        """
        # Parse metadata first (validates structure)
        metadata = self._parse_metadata(raw_data)

        # Parse required DataFrames
        job_data = self._parse_dataframe(raw_data, "jobData")
        stage_data = self._parse_dataframe(raw_data, "stageData")
        task_data = self._parse_dataframe(raw_data, "taskData")
        accum_data = self._parse_dataframe(raw_data, "accumData")

        # Parse optional DataFrames
        sql_data = None
        if metadata.exists_sql:
            if "sqlData" not in raw_data:
                raise ValueError(
                    "Metadata indicates SQL data exists (existsSQL=True) but 'sqlData' "
                    "key is missing from raw data"
                )
            sql_data = self._parse_dataframe(raw_data, "sqlData")

        executor_data = None
        if metadata.exists_executors:
            # Handle both "executors" and "executorData" keys (legacy support)
            if "executors" not in raw_data and "executorData" not in raw_data:
                raise ValueError(
                    "Metadata indicates executor data exists (existsExecutors=True) but "
                    "neither 'executors' nor 'executorData' keys found in raw data"
                )
            executor_key = "executors" if "executors" in raw_data else "executorData"
            executor_data = self._parse_dataframe(raw_data, executor_key)

        # Build immutable SparkApplication
        # The __post_init__ will validate consistency between metadata and data
        return SparkApplication(
            metadata=metadata,
            job_data=job_data,
            stage_data=stage_data,
            task_data=task_data,
            accum_data=accum_data,
            sql_data=sql_data,
            executor_data=executor_data,
        )
