# Copyright (c) 2025 Databricks, Inc.
# Licensed under the Databricks Open Model License. See LICENSE for the full text.
"""O7 integration: `starboard-maint rules install` deploys the shipped X7 rulesets.

Validates that the maint rules backend, run against the REAL committed ``plugin/rules/``
source tree (generated by ``scripts/gen_rulesets.py``), deploys every ruleset into a
consumer's ``.isaac/rules/``: the umbrella router ``starboard.md`` plus the six namespaced
per-domain files ``starboard-<domain>.md``. Guards the E1 (backend) ↔ X7 (generator)
filename contract so the two never silently drift out of sync again.
"""

from __future__ import annotations

from pathlib import Path

from starboard_skills.maint.backends import rules


def _repo_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "plugin" / "rules").is_dir():
            return parent
    raise AssertionError("could not locate repo root containing plugin/rules/")


PLUGIN_RULES = _repo_root() / "plugin" / "rules"
EXPECTED_DEPLOYED = {
    "starboard.md",  # umbrella/router (domain "baseline")
    "starboard-jobs.md",
    "starboard-sql.md",
    "starboard-warehouse.md",
    "starboard-uc.md",
    "starboard-cluster.md",
    "starboard-discovery.md",
}


def test_rules_install_deploys_all_shipped_rulesets(tmp_path: Path) -> None:
    dest = tmp_path / ".isaac" / "rules"
    extra = rules.install(PLUGIN_RULES, dest)

    # Nothing reported missing — the backend found every source file it expects.
    assert extra["missing_domains"] == [], (
        f"maint rules backend could not find shipped rulesets: {extra['missing_domains']} "
        f"(E1 backend ↔ X7 generator filename drift?)"
    )

    deployed_files = {p.name for p in dest.glob("*.md")}
    assert deployed_files >= EXPECTED_DEPLOYED, (
        f"missing deployed rulesets: {EXPECTED_DEPLOYED - deployed_files}"
    )

    # verify() round-trips clean against the real source.
    ok, msg = rules.verify(PLUGIN_RULES, dest)
    assert ok, msg


def test_rules_remove_reverses_install(tmp_path: Path) -> None:
    dest = tmp_path / ".isaac" / "rules"
    rules.install(PLUGIN_RULES, dest)
    rules.remove(dest)
    leftover = {p.name for p in dest.glob("*.md")} & EXPECTED_DEPLOYED
    assert not leftover, f"rules remove left files behind: {leftover}"
