# Databricks notebook source
# Generated by Starboard — review before running; nothing here writes to your workspace until you uncomment it.
#
# TEMPLATE INSTRUCTIONS (host fills these before delivering):
#   Replace every {{PLACEHOLDER}} with the real value for this opportunity.
#   Delete these instruction comments before sending the notebook to the operator.
#
# Notebook structure:
#   Cell 1 — title / markdown: finding summary, sizing, evidence citation
#   Cell 2 — READ-ONLY evidence query: reproduces the cited number, parameterized to workspace_id
#   Cell 3 — enumeration: lists the specific targets to act on
#   Cell 4 — remediation: the exact commands, COMMENTED OUT and gated (capture → apply → rollback)
#   Cell 5 — post-change measurement (perf_metric / pilot items; optional for bounded_dbu): the
#            measurement query run separately for a baseline window and an after window
#
# Variants — pick the one that matches the backlog item's sizing.kind and delete the other:
#   bounded_dbu        Cell 1 states the bounded DBU and its arithmetic; Cell 2 is the
#                      "bounded_dbu" billing query that reproduces that DBU figure.
#   perf_metric/pilot  No DBU figure is assumed. Cell 1 states the metric (perf_metric) or what the
#   (and none)         pilot measures; Cell 2 is the "perf_metric / pilot" query that reproduces the
#                      metric by day (the baseline); Cell 5 runs the id's measurement query for
#                      a baseline window and an after window, each scoped to the target.
#                      Delete the recoverable-DBU lines in Cell 1.
#
# {{FINDING_SUMMARY}} is the finding itself (backlog `finding` / `summary`, else `title`) — never the
# lever; the lever goes in Cell 4. A backlog `lever_command`
# {"kind": "cli"|"sql"|"json"|"bundle_yaml", "text": "..."} is pasted verbatim (commented out) into
# Cell 4; `starboard-helper notebook render` does this for you (and writes the notebook path into the
# backlog item's `notebook` field).
# No angle-bracket placeholder (e.g. a literal "<before>") may remain in the delivered notebook.

# COMMAND ----------

# MAGIC %md
# MAGIC # {{FINDING_TITLE}}
# MAGIC
# MAGIC **Finding:** {{FINDING_SUMMARY}}
# MAGIC
# MAGIC > Example: "32 Vector Search endpoints have received no queries in the last 30 days
# MAGIC > but continue to accrue DBU against the `VECTOR_SEARCH` SKU."
# MAGIC
# MAGIC **Sizing ({{SIZING_KIND}}):** {{SIZING_VALUE}} {{SIZING_UNIT}} — {{SIZING_FORMULA}}
# MAGIC
# MAGIC > perf_metric example: `23.6 queued_pct (peak day)` — daily queued share from the warehouse
# MAGIC > queue query; re-measured 7 days after the change (Cell 5).
# MAGIC > pilot example: `pilot — measure DBU per run and wall-clock per run on job 666902181250446 for 7 days vs the
# MAGIC > prior 7 days`. No DBU figure is claimed until the pilot has run.
# MAGIC
# MAGIC <!-- bounded_dbu only — delete these lines for perf_metric / pilot / none items -->
# MAGIC **Expected recoverable DBU:** {{RECOVERABLE_DBU}} DBU (list-price estimate)
# MAGIC
# MAGIC Arithmetic: `{{RECOVERABLE_DBU_ARITHMETIC}}`
# MAGIC
# MAGIC > Example: `14 endpoints × 2,940 DBU/30d = 41,160 DBU`  ← per-unit figure already scoped to the window; no rate × days form.
# MAGIC
# MAGIC **Evidence citation:**
# MAGIC - Query: `{{QUERY_ID}}`
# MAGIC - Billing row / pack reference: `{{ROW_REFERENCE}}`
# MAGIC - Workspace: `{{WORKSPACE_ID}}`
# MAGIC
# MAGIC **Backlog tier:** {{BACKLOG_TIER}} &nbsp;|&nbsp; **Confidence:** {{CONFIDENCE}}/10

# COMMAND ----------

# READ-ONLY — this cell does not modify anything.
# VARIANT bounded_dbu: reproduces the DBU figure cited above against system.billing.usage.
# (perf_metric / pilot / none items: delete this cell and keep the next one.)
# Run this first to confirm the number before acting on anything.

workspace_id = "{{WORKSPACE_ID}}"  # scope: this notebook covers exactly this workspace

result = spark.sql(f"""
    SELECT
        workspace_id,
        {{GROUPING_DIMENSIONS}},                 -- e.g. sku_name, endpoint_name, job_id
        ROUND(SUM(usage_quantity), 2)  AS total_dbus   -- DBU via usage_quantity (the real column)
    FROM system.billing.usage
    WHERE workspace_id    = '{workspace_id}'
      AND {{PRODUCT_FILTER}}                      -- e.g. billing_origin_product = 'VECTOR_SEARCH'
      AND {{DATE_RANGE_FILTER}}                   -- e.g. usage_date >= date_sub(current_date(), 30)
    GROUP BY workspace_id, {{GROUPING_DIMENSIONS}}
    ORDER BY total_dbus DESC
""")

result.display()

# Expected: total_dbus in the result should match {{RECOVERABLE_DBU}} within rounding.
# If it differs materially, stop — do not proceed to the remediation cell — and re-verify the finding.

# COMMAND ----------

# READ-ONLY — this cell does not modify anything.
# VARIANT perf_metric / pilot / none: reproduces the cited metric by day (the baseline).
# No DBU figure is assumed. (bounded_dbu items: delete this cell and keep the one above.)
# Replace the example query with the catalog entry's verify query in public system.* names,
# e.g. daily queueing on one SQL warehouse:

workspace_id = "{{WORKSPACE_ID}}"
metric_target_id = "{{TARGET_ID}}"  # the warehouse or job id named in the finding

metric = spark.sql(f"""
    SELECT
        DATE(start_time)                                                  AS day,
        COUNT(*)                                                          AS queries,
        ROUND(100 * AVG(CASE WHEN waiting_at_capacity_duration_ms > 0 THEN 1 ELSE 0 END), 1)
                                                                          AS queued_pct,
        ROUND(PERCENTILE(waiting_at_capacity_duration_ms, 0.95) / 1000, 1) AS p95_capacity_wait_s
    FROM system.query.history
    WHERE workspace_id = '{workspace_id}'
      AND compute.warehouse_id = '{metric_target_id}'
      AND start_time >= date_sub(current_date(), 7)
      AND start_time <  current_date()                                     -- full days only
    GROUP BY DATE(start_time)
    ORDER BY day
""")

metric.display()

# Expected: the metric matches {{SIZING_VALUE}} {{SIZING_UNIT}} from the evidence pack within rounding.
# If it differs materially, stop and re-verify the finding before acting.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Targets enumerated
# MAGIC
# MAGIC The following **{{TARGET_TYPE}}** (e.g. "Vector Search endpoints", "Lakebase instances",
# MAGIC "idle SQL warehouses") were identified in the query above as contributing to the finding.
# MAGIC
# MAGIC Confirm this list matches the query output in Cell 2 before proceeding.
# MAGIC
# MAGIC > Examples of well-formed targets:
# MAGIC > - Vector Search abandoned endpoints: `ka-<id>`, `mas-<id>` (name pattern from the inventory join)
# MAGIC > - Dormant Lakebase instances: instance IDs from the Lakebase inventory + usage-timestamp join
# MAGIC > - Idle SQL warehouses: warehouse IDs with zero queries in the billing window

# COMMAND ----------

# Enumerate specific targets — review and confirm before proceeding to the remediation cell.
# Populate from the query output above; do not hard-code IDs without verifying they are still live.

targets = [
    # ("{{TARGET_ID_1}}", "{{TARGET_NAME_1}}", "{{TARGET_DESCRIPTION_1}}"),
    # ("{{TARGET_ID_2}}", "{{TARGET_NAME_2}}", "{{TARGET_DESCRIPTION_2}}"),
    # ... add one tuple per target from the query output
]

if not targets:
    raise ValueError("No targets populated — fill in the targets list from the query output above.")

print(f"Targets listed for verification ({len(targets)}) — confirm each is still live before acting:")
for target_id, target_name, description in targets:
    print(f"  id={target_id}  name={target_name}  —  {description}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Remediation
# MAGIC
# MAGIC **Destructive — operator action required.**
# MAGIC
# MAGIC The commands in the next cell are **commented out**. They modify or stop live resources.
# MAGIC Before uncommenting any line:
# MAGIC 1. Re-run the evidence cell (Cell 2) to confirm the cited figure is still accurate.
# MAGIC 2. Confirm each target in the list above still exists and is owned by this workspace.
# MAGIC 3. Uncomment and run **one target at a time** — not the whole loop at once.
# MAGIC
# MAGIC Nothing executes until you uncomment it.

# COMMAND ----------

# DESTRUCTIVE — REVIEW BEFORE UNCOMMENTING
# These commands modify or terminate live resources in workspace {{WORKSPACE_ID}}.
# Verify each target above before uncommenting.

#
# Lever (from the action plan):
#   {{LEVER}}

# Command — the concrete CLI / SQL / JSON for this target, not prose. Example (OPP-JOB-OVERLAP,
# act_now, preconditions confirmed, job not bundle-deployed):
# 1) Capture the current settings (needed for rollback):
# databricks jobs get {{TARGET_ID}} > job-{{TARGET_ID}}-before.json
# 2) Apply:
# databricks jobs update {{TARGET_ID}} --json '{"new_settings": {"max_concurrent_runs": 1, "queue": {"enabled": false}}}'
#
# Rollback:
# restore from job-{{TARGET_ID}}-before.json (captured above)
#
# OPP-JOB-OVERLAP when the item is Investigate or a cadence / backfill precondition is not met:
# no command — an operator decision note listing what the owner must confirm first.
# Bundle-managed job — ANY job lever (overlap, timeout, performance_target) when
# vt-job-settings-history says deployment_kind = BUNDLE or the lever says "in the bundle": change
# the bundle source, not the deployed job (a `jobs update` is overwritten by the next deploy):
#   max_concurrent_runs: 1
#   queue:
#     enabled: false
# then redeploy the bundle (`databricks bundle deploy`); roll back in the bundle source too.
#
# Other common shapes (real ids and values only):
#   databricks warehouses edit c389980b7b55cfb6 --max-num-clusters 2          (OPP-WH-QUEUE)
#   databricks warehouses edit ca580fec2da67daf --cluster-size Medium         (OPP-WH-RESIZE)
# Warehouse direction: Apply sets the lever's PROPOSED value; Rollback restores the CURRENT value
# (from vt-warehouse-config-history, else the X in the lever's "X → Y"). If the proposed value
# equals the current one or contradicts the lever, write a decision note instead of a command.
#   jobs update ... {"new_settings": {"performance_target": "STANDARD"}}       (OPP-SERVERLESS-STANDARD-MODE)
#   jobs update ... {"new_settings": {"timeout_seconds": 12000}}               (OPP-JOB-TIMEOUT)
# Uncomment and run one target at a time.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Post-change measurement
# MAGIC
# MAGIC Run this **8 or more days after** the change (perf_metric and pilot items; optional for bounded_dbu).
# MAGIC It runs the measurement query twice — a baseline window (the 7 full days before the change) and
# MAGIC an after window (the 7 full days from the day after it) — scoped to this target, and compares the
# MAGIC catalog metric between them, so the effect is measured, not assumed.

# COMMAND ----------

# READ-ONLY — post-change measurement: a baseline window and an after window, run separately.
# Each window is its own query, so per-day / per-run figures use that window's own denominators.
# Every window has an explicit start AND end (start + 7 full days) — never an open-ended
# `< current_date()`, which silently grows the after window when the notebook is run later.
# Scope it to the exact cited population: the cited source_type / source_id / client_application
# for OPP-WH-SCAN (not a warehouse-wide average); successful CRON parent runs and the wait task's
# successful, non-zero-duration attempts for OPP-JOB-WAIT-TASK.
# Measure the catalog's canonical metric (sizing.metric) on the target, e.g. for
# OPP-SERVERLESS-STANDARD-MODE: CRON DBU per run and wall-clock per run of the target job
# (vt-job-runs), not the workspace performance-mode mix. Example: daily queueing on one warehouse.
import datetime as _dt  # noqa: E402

change_date = ""  # YYYY-MM-DD the operator applied the change — enter it; never pre-fill a historical timestamp
if not change_date:
    raise ValueError("Set change_date (YYYY-MM-DD) before running the post-change measurement.")
_c = _dt.date.fromisoformat(change_date)
_day = lambda n: str(_c + _dt.timedelta(days=n))  # noqa: E731
windows = {
    "baseline": (_day(-7), _day(-1)),  # the 7 full days before the change
    "after": (_day(1), _day(7)),       # the first full day after the change, for 7 days
}

for name, (start, end) in windows.items():
    spark.sql(f"""
        SELECT
            '{name}'                                                                       AS comparison_window,
            COUNT(*)                                                                         AS queries,
            ROUND(100 * AVG(CASE WHEN waiting_at_capacity_duration_ms > 0 THEN 1 ELSE 0 END), 1) AS queued_pct,
            ROUND(PERCENTILE(waiting_at_capacity_duration_ms, 0.95) / 1000, 1)               AS p95_capacity_wait_s
        FROM system.query.history
        WHERE workspace_id = '{workspace_id}'
          AND compute.warehouse_id = '{metric_target_id}'
          AND start_time >= DATE'{start}'
          AND start_time <  DATE_ADD(DATE'{end}', 1)
    """).display()

# Replace the example with the item's measurement query; `starboard-helper notebook render` builds it.

# COMMAND ----------

# MAGIC %md
# MAGIC ---
# MAGIC *Generated by Starboard. DBU figures are list-price estimates unless otherwise labeled.*
# MAGIC *Nothing in this notebook writes to your workspace until you uncomment the remediation cell.*
# MAGIC *After acting, run the post-change measurement (or re-run Cell 2) to confirm the figures moved in the expected direction.*
